-- A component export, kept by the installation under a name.
--
-- V100 made a component travel as a file: a versioned JSON envelope holding no
-- ids and no secrets, which one workspace downloads and another uploads. That
-- works and it is entirely person-carried - the file lives in somebody's
-- Downloads folder, and the second team that wants the same function has to
-- find the first team to get it.
--
-- A template is that envelope with a name on it, stored here. Nothing else. The
-- "Use template" button is the import that already exists, pointed at a row in
-- this table rather than at an upload, so there is exactly one format, one
-- parser, one set of rules about renaming on collision, and one refusal for a
-- version this installation does not read.
--
-- Installation-wide, with no workspace column, and that is the point rather
-- than an omission: one team's work becoming available to every team is the
-- whole reason to have this. It is also why creating one is an administrator's
-- act - a template published here is offered to workspaces its author cannot
-- see - while using one is open to anybody who may already write to the
-- workspace they are importing into.
CREATE TABLE component_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What it is called on the page, and unique installation-wide for the same
    -- reason a shell's name is: this is one list that everybody reads, and two
    -- rows called "Order handling" are two rows nobody can choose between.
    name VARCHAR(120) NOT NULL,

    -- Why somebody would use it. Nullable because the column cannot make
    -- anybody write a useful sentence, but the page asks for one: a template
    -- called "helpers" with nothing beside it is a row people scroll past.
    description VARCHAR(1000),

    -- The envelope itself, exactly as the export wrote it.
    --
    -- TEXT, and never parsed by the database. A deep export of a function with
    -- the objects it is typed against runs to a few kilobytes and one of a
    -- skill's markdown can run to more, so there is no honest limit to pick.
    --
    -- What it holds - which kinds, how many, which format version - is
    -- deliberately *not* copied into columns beside it. It is derivable by
    -- reading the envelope, and a copy in a column is a second answer that can
    -- disagree with the file after somebody replaces it. The list page parses
    -- what it shows, which costs one small JSON parse per row on one admin
    -- screen.
    envelope TEXT NOT NULL,

    -- Who published it and when. A template outlives the workspace it was taken
    -- from and the person who took it, and the row deliberately holds no
    -- pointer back to either: it is a snapshot, and a link would suggest that
    -- editing the original changes the template, which it does not.
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(255) NOT NULL,

    -- Moved by a rename, a reworded description, or a replaced file - which is
    -- how a template is brought up to date, since it does not follow anything.
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_by VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX component_template_name_key ON component_template (name);
