-- What an agent and whoever is talking to it have said to each other, kept
-- somewhere no single run owns.
--
-- Everything an agent said until now belonged to whatever asked it. A chat's
-- turns live under the chat session and end with it; a workflow's live in the
-- run's log, which is a record of the run rather than of the conversation, and
-- is read on the run's page and nowhere else. So an agent asked the same
-- question by two workflows had no way of knowing it had ever been asked, and
-- nobody had one page to read what it has been told over a week.
--
-- This is that page. It is keyed by something the caller computes rather than
-- by a run, a workflow or a chat - which is the whole mechanism: two workflows
-- that arrive at the same key are talking into the same session on purpose, and
-- that is how a conversation outlives the run that started it. A key that
-- collides is not a fault to be defended against here; a key that is *not*
-- shared is what an id would have given, and an id is what this deliberately
-- does not use.
CREATE TABLE llm_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Whose it is. An agent belongs to a workspace and so does everything it
    -- says, which is also what makes the key only have to be unique here: two
    -- teams that both keyed a session on "standup" are not in one conversation.
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    /*
     * The identity, composed once and stored composed.
     *
     * It is `prefix:key`, or the key alone where no prefix was given, and the
     * separator is not decoration. Plain concatenation would make prefix
     * "issue-" with key "42" the same session as no prefix with key "issue-42",
     * and those are two callers who meant different things being quietly joined
     * - which is the one kind of collision that is *not* the point of this
     * table. Composition lives in LlmSessionKey and nowhere else, so this
     * column never holds two spellings of the same intent.
     */
    session_key VARCHAR(300) NOT NULL,

    /*
     * The prefix as it was given, or null where there was none.
     *
     * Kept beside the composed key rather than derived back out of it, because
     * a prefix may itself contain the separator and there would be no way to
     * tell which colon was ours. It is what lets a list be narrowed to one
     * family of sessions without anybody parsing a key.
     */
    key_prefix VARCHAR(120),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    /*
     * When anything was last said here, or null on a session that has been
     * opened and not yet written to.
     *
     * Denormalised on purpose: the list is read by recency, and a max() over
     * the events would sort a page by joining every row of every session in the
     * workspace. The recorder is the only thing that writes an event and it
     * moves this in the same breath.
     */
    last_event_at TIMESTAMPTZ
);

-- The identity, enforced. Two runs racing to open the same session is expected
-- and this is what makes the loser find the winner's row rather than make a
-- second one.
CREATE UNIQUE INDEX llm_session_key_key ON llm_session (workspace_id, session_key);

-- How the page opens: this workspace's sessions, most recently spoken in first.
CREATE INDEX llm_session_recent_idx ON llm_session (workspace_id, last_event_at DESC);

-- One thing that happened in a session.
--
-- Four kinds, which are the four things there are to record and not a taxonomy:
-- what the agent said, a tool it called, what was said to it, and a note from
-- the machinery about something that happened to the conversation itself.
CREATE TABLE llm_session_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id BIGINT NOT NULL REFERENCES llm_session (id) ON DELETE CASCADE,

    -- AGENT, TOOL, USER or SYSTEM. No CHECK: the enum is enforced where the
    -- rows are written, and a constraint here would have to be widened in two
    -- schemas every time a kind is added, which is the failure this codebase
    -- has already had once.
    kind VARCHAR(16) NOT NULL,

    /*
     * Who or what produced it: the agent's name, the tool's name, the node or
     * the person that asked, "system" for a note. Never null - a transcript
     * that cannot say who spoke is not a transcript - and a name rather than an
     * id, so it stays readable after the agent it names has been renamed or
     * deleted.
     */
    actor VARCHAR(200) NOT NULL,

    /*
     * The payload, and what it is depends on the kind: the words for what was
     * said, the call's arguments as the model sent them for a tool, the note
     * for a system line.
     *
     * One column rather than one per kind. A model's answer and a tool's
     * arguments are both "the body of this event" to everything that reads
     * them - the page shows it, the search matches it - and four nullable
     * columns of which exactly one is ever filled is a shape that has to be
     * re-explained at every join.
     *
     * TEXT because there is no honest limit: an answer is bounded by the
     * model's context window and a tool's arguments by whatever the model felt
     * like sending.
     */
    content TEXT,

    at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One session's transcript, in order. The id is in the index because a turn
-- writes its question, its tool calls and its answer inside the same
-- millisecond, and a transcript that reorders itself between two reads is a
-- transcript nobody trusts.
CREATE INDEX llm_session_event_session_idx ON llm_session_event (session_id, at, id);
