-- One issue said to have something to do with another.
--
-- The tracker could hang a web address on an issue since V90, and the thing
-- people most wanted to hang there was another issue in this same tracker -
-- which came out as a URL that says nothing until it is clicked, goes stale the
-- moment the issue is moved to another workspace and is invisible from the
-- other end. A duplicate filed twice was two reports neither of which knew
-- about the other, and "we cannot start this until the connector lands" lived
-- in a comment nobody scrolled to.
--
-- Three relations, five names. RELATES_TO is the honest cheap one and means
-- only "read that one too". BLOCKS and DUPLICATES are directed and are each
-- read from either end - #4 blocks #7 is the same fact as #7 is blocked by #4 -
-- so what is stored is the relation pointing one way and the reader is shown
-- whichever half faces them. Parent and child are deliberately absent: a parent
-- is a promise about aggregation - a status derived from its children, a tree
-- to walk, a depth to guard - and this tracker has none of that, so a parent
-- link would be a "relates to" wearing a word that makes people expect a roll-up
-- that never comes.
CREATE TABLE workspace_issue_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * The two ends, and the row is the whole link rather than one half of it.
     *
     * A row per end would be two rows that can disagree - one deleted, one left,
     * and an issue that says it blocks something the other end has never heard
     * of. Stored once, it cannot be half made, and taking it off from either end
     * is the same delete.
     *
     * Which end is which is decided by the relation rather than by who typed it:
     * BLOCKS runs from the blocker to the blocked, DUPLICATES from the copy to
     * the original, and RELATES_TO - which reads the same both ways - is stored
     * with the lower id first so the same pair cannot be written twice wearing
     * opposite ends.
     *
     * Row ids rather than the numbers people say, for the reason the history is
     * keyed by the id: a number is per workspace and an issue that moves is
     * given a free one where it lands, so a link keyed by the number would
     * follow whatever is filed next.
     */
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,
    other_issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,

    -- RELATES_TO, BLOCKS or DUPLICATES. The other two names a reader sees -
    -- blocked by, duplicated by - are these read from the far end and are never
    -- stored, because storing both would be storing one fact twice.
    kind VARCHAR(16) NOT NULL,

    linked_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Who said so, and so the only person who may take it back off. A name
    -- rather than a foreign key, like the reporter of an issue: whoever linked
    -- two issues stays whoever linked them after their row is gone.
    linked_by VARCHAR(120) NOT NULL DEFAULT ''
);

-- Two issues are connected in one way or not at all. A pair that both blocked
-- and merely related would be one line contradicting the other, and a pair that
-- blocked in both directions would be a contradiction the reader has to notice.
-- This index refuses the pair one way round; the other way is refused where the
-- link is made, because an index over an unordered pair is an expression index
-- and this schema is written twice in two dialects.
CREATE UNIQUE INDEX workspace_issue_relation_pair_key
    ON workspace_issue_relation (issue_id, other_issue_id);

-- An issue's links are read from both ends at once, so the far end needs an
-- index of its own; the near end already has the unique one above.
CREATE INDEX workspace_issue_relation_other_idx
    ON workspace_issue_relation (other_issue_id, linked_at);
