-- What starts a workflow: an event arriving on a connection, or the clock.
-- Named workflow_trigger because `trigger` is reserved in SQL.
CREATE TABLE workflow_trigger
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id       BIGINT       NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    -- What it starts. A trigger without one could not do its job.
    workflow_id   BIGINT       NOT NULL REFERENCES workflow (id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    type          VARCHAR(24)  NOT NULL,
    -- The team connection an incoming event arrives on. The connection module
    -- owns that table, so this is a plain column with no foreign key.
    connection_id BIGINT,
    -- Which event on that connection; null for a scheduled trigger.
    action        VARCHAR(32),
    -- A cron expression and the zone it is read in; null for an incoming one.
    cron          VARCHAR(120),
    timezone      VARCHAR(64),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_workflow_trigger_name UNIQUE (team_id, name),
    CONSTRAINT ck_workflow_trigger_type CHECK (type IN ('INCOMING_CONNECTION', 'SCHEDULED')),
    CONSTRAINT ck_workflow_trigger_action
        CHECK (action IS NULL OR action IN ('MENTION', 'REPLY', 'MESSAGE', 'ISSUE_CREATED', 'ISSUE_UPDATED')),
    -- An incoming trigger needs a connection and an event; a scheduled one needs
    -- a cron expression. Neither is any use without them.
    CONSTRAINT ck_workflow_trigger_shape CHECK (
        (type = 'INCOMING_CONNECTION' AND connection_id IS NOT NULL AND action IS NOT NULL)
            OR (type = 'SCHEDULED' AND cron IS NOT NULL)
        )
);

CREATE INDEX idx_workflow_trigger_team ON workflow_trigger (team_id);
-- What the Slack listener asks: which triggers wait on this connection?
CREATE INDEX idx_workflow_trigger_connection ON workflow_trigger (connection_id, action) WHERE enabled;
