-- What a component was, kept so it can be looked at and put back.
--
-- A workspace's functions, tools, skills and agents are edited in place. A save
-- overwrites the row, and until now the previous text existed nowhere: an
-- accidental paste over a prompt somebody spent a week on was gone the moment
-- the form was submitted. The audit log records that a function was updated and
-- nothing about what it said, which is the one thing anybody wants back.
--
-- So the displaced state is written down. Not the new state: a revision is
-- recorded *before* a save replaces what was there, stamped with that state's
-- own last_modified_at and last_modified_by rather than with the moment it was
-- displaced. Two things follow, and both are the reason for doing it this way.
-- The live row is always the newest revision, so nothing has to be copied twice
-- to keep the two in step; and a component that has existed since before this
-- table did gets its history the first time somebody edits it, with no backfill
-- to write and no revision claiming to hold a state nobody ever saved.
--
-- Snapshots are JSON written by hand rather than by reflection, for the reason
-- workflow_publication gives: a shape stored in a database outlives the class
-- it came from. They name what they reference by id - the object a parameter is
-- typed against, the model an agent thinks with - and never by name, because a
-- rename would otherwise make an old revision restore to a different thing.
CREATE TABLE component_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Whose it is. A foreign key rather than a plain column, because it is the
     * only key here that can have one: this table holds four kinds of component
     * living in four tables, so component_id below points at whichever of them
     * `kind` names and cannot reference any of them.
     */
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    /* FUNCTION, TOOL, SKILL or AGENT. WORKFLOW is not here: a workflow's
     * versions are its publications, which workflow_publication already holds. */
    kind VARCHAR(16) NOT NULL,

    /* The component's row id in the table `kind` names. No foreign key, so a
     * deleted component's revisions are removed by the delete that removed it
     * rather than by the database - see ComponentRevisionRecorder.forget. */
    component_id BIGINT NOT NULL,

    /* What it was called then, so a list of revisions can be read without
     * parsing every snapshot, and a rename is visible in the history. */
    name VARCHAR(120) NOT NULL,

    -- When this state was saved, and by whom: the component's own stamps, not
    -- the moment it was displaced. Never null - a history that cannot name
    -- anybody is a rumour.
    saved_at TIMESTAMPTZ NOT NULL,
    saved_by VARCHAR(120) NOT NULL,

    /* When the row was written, which is when the state stopped being current.
     * What the retention sweep measures, because retention is about how long
     * something has been *history*, not how old the work was. */
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    snapshot TEXT NOT NULL
);

-- One component's history, newest first, which is the only way it is read.
CREATE INDEX component_revision_component_idx
    ON component_revision (kind, component_id, recorded_at DESC, id DESC);

-- What the retention sweep asks for: everything older than a date, across
-- every workspace and every kind.
CREATE INDEX component_revision_recorded_idx ON component_revision (recorded_at);

-- A workflow's publications are its versions, so they stop being overwritten.
--
-- The table held exactly one row per workflow, replaced on every publish, which
-- made "what did this run last month" unanswerable. A version of a workflow is
-- a publication and not a draft - a draft is a draft, the way a commit on main
-- is not a release - so keeping them is what gives a workflow a history at all.
--
-- The existing rows are the point of doing it this way rather than with a new
-- table: whatever is published right now goes on running, becomes the first
-- entry of its workflow's history, and nothing has to be republished.
ALTER TABLE workflow_publication DROP CONSTRAINT workflow_publication_pkey;
ALTER TABLE workflow_publication ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

/*
 * The publication this one is a copy of, when it was made by restoring.
 *
 * Restoring publishes again rather than reviving a row, so the newest
 * publication is always the one that runs and the history only ever grows -
 * the same shape as reverting a commit rather than deleting one. This says
 * which older publication was copied, so the history can say so too.
 */
ALTER TABLE workflow_publication ADD COLUMN restored_from BIGINT;

-- One workflow's publications, newest first. The id is in it because the
-- newest row is what runs, and two publications a second apart must not be
-- able to swap places between two reads.
CREATE INDEX workflow_publication_workflow_idx ON workflow_publication (workflow_id, id DESC);

-- An agent gains the two stamps every other versioned component already had.
--
-- A revision holds the state that was displaced, stamped with when *that* state
-- was saved and by whom, and an agent was the one of the four that recorded
-- neither. Without them an agent's history could only say when each version
-- stopped being current, which is the question nobody asks.
--
-- Existing agents are stamped with the moment of the upgrade and nobody, which
-- is what is actually known about them: the row says when it was last written
-- only from here on.
ALTER TABLE agent ADD COLUMN last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE agent ADD COLUMN last_modified_by VARCHAR(120) NOT NULL DEFAULT '';
