-- Libraries: JavaScript an installation loads once and its scripts import.
--
-- A library here is a stored artefact rather than a name from a registry, and the
-- reason is that the only two ways to honour a registry name are both shut.
-- Fetching one at run time would mean giving the sandbox a network, which is the
-- thing it exists to withhold; fetching it at upload would mean this server
-- reaching out to a registry, which makes an offline installation unusable and
-- makes what a workspace runs depend on what a registry served that afternoon.
--
-- It is the installation's rather than a workspace's, because the question an
-- installation has to be able to answer is what code is running inside it. A
-- library each workspace uploaded for itself would give that question as many
-- answers as there are workspaces, and would spread the useful half of it - which
-- functions and tools depend on this - across screens no administrator can see.
CREATE TABLE script_library
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_key      VARCHAR(64)  NOT NULL,
    name             VARCHAR(200) NOT NULL,
    filename         VARCHAR(255) NOT NULL,
    source           TEXT         NOT NULL,
    -- What it was written in, where that was TypeScript. Never evaluated: it is
    -- kept so the library can be downloaded as the thing somebody wrote.
    typescript       TEXT,
    size_bytes       BIGINT       NOT NULL,
    sha256           VARCHAR(64)  NOT NULL,
    -- What its default export turned out to hold, read once by evaluating it.
    -- Not a type declaration: nothing in a bundle says what its arguments are,
    -- and this claims only that a member is something to call or something to
    -- read. The editor annotates `imports` from it.
    declared_members TEXT         NOT NULL DEFAULT '[]',
    -- Whether the export is itself something to call, rather than an object.
    callable         BOOLEAN      NOT NULL DEFAULT FALSE,
    uploaded_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    uploaded_by      VARCHAR(120) NOT NULL DEFAULT '',
    -- Its identity, not the file's: uploading the same key again replaces what is
    -- loaded under it, which is how a library is updated in place without every
    -- function that imports it having to be repointed.
    CONSTRAINT uq_script_library_key UNIQUE (library_key)
);

-- What a function imports from the installation's libraries.
--
-- A second table rather than a kind column beside the function one. The two lists
-- point at two different tables, and one column that could mean either is one
-- column that will one day mean the wrong one - which for an import is a call into
-- whatever happened to have that id.
CREATE TABLE workflow_function_library
(
    function_id BIGINT      NOT NULL REFERENCES workflow_function (id) ON DELETE CASCADE,
    position    INTEGER     NOT NULL,
    imported_id BIGINT      NOT NULL,
    import_name VARCHAR(64) NOT NULL,
    PRIMARY KEY (function_id, position),
    CONSTRAINT uq_workflow_function_library_name UNIQUE (function_id, import_name)
);

CREATE TABLE agent_tool_library
(
    tool_id     BIGINT      NOT NULL REFERENCES agent_tool (id) ON DELETE CASCADE,
    position    INTEGER     NOT NULL,
    imported_id BIGINT      NOT NULL,
    import_name VARCHAR(64) NOT NULL,
    PRIMARY KEY (tool_id, position),
    CONSTRAINT uq_agent_tool_library_name UNIQUE (tool_id, import_name)
);

-- What imports a given library, which is what an administrator asks before
-- replacing or removing one.
CREATE INDEX ix_workflow_function_library_imported ON workflow_function_library (imported_id);
CREATE INDEX ix_agent_tool_library_imported ON agent_tool_library (imported_id);
