-- The answers a chat has been asked to give again, and what it said the first
-- time.
--
-- Issue #245 asked for the last answer to be regenerated. Asking again means
-- the model is given the conversation with its own last turn taken back off it,
-- which is the only way it can answer the same question twice - a thread
-- holding two answers to one question is a thread that has never been said out
-- loud, and the second one would be answering the first.
--
-- So a regenerate throws an answer away, and this is the table that stops it
-- being thrown away. Somebody presses it because the answer was not what they
-- wanted; they press it once more and the one they had is the one they wanted
-- after all. That happened to be the whole point of the button, and losing the
-- earlier take makes the button a coin toss you cannot call twice.
--
-- **This is not a messages table**, and the rule against one still stands. The
-- conversation lives in `spring_ai_chat_memory` keyed by a conversation id,
-- because a workflow run keys one the same way and every agent in it shares the
-- thread. What is here was deliberately taken *out* of that thread: it is not
-- part of the conversation, it is never put in front of a model, and nothing
-- but the chat screen reads it. `chat_session` holds what the store has no
-- opinion about, and so does this.
CREATE TABLE chat_answer_take (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    chat_session_id BIGINT NOT NULL REFERENCES chat_session (id) ON DELETE CASCADE,

    -- Which answer this is an earlier take of: its place in the thread, counted
    -- from the start.
    --
    -- A position rather than a message id, because Spring AI's store gives a
    -- message no id at all - it keeps a conversation, a role, some text and an
    -- order. The position is stable for the life of a chat: the thread is only
    -- ever appended to, and a regenerate replaces the last turn in place rather
    -- than inserting anything, so nothing after an answer can move it.
    message_index INTEGER NOT NULL,

    -- What was said that time. Kept whole: a truncated earlier answer is one
    -- nobody can go back to, which is what this exists to allow.
    content TEXT NOT NULL,

    taken_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One chat's earlier takes, in the order they were said. The id is in the index
-- because two takes of one answer can land in the same instant on a fast model,
-- and a history that reorders itself between two reads is not one.
CREATE INDEX chat_answer_take_session_idx
    ON chat_answer_take (chat_session_id, message_index, id);
