-- A problem given to an agent, and the agent working at it until it is done.
--
-- A workflow run walks a graph somebody drew; a chat is one exchange at a time
-- with a person waiting at the other end. A task is neither: the shape of the
-- work is not known when it starts, and nobody is sitting there between the
-- turns. What is written down is therefore small - what was asked, who is doing
-- it, how far it has got and what it may spend - because everything that
-- actually happened is in the LLM session this points at. There is no second
-- transcript here on purpose.
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    /*
     * A line to find it by in a list, taken from the first line of the prompt
     * where nobody supplied one.
     *
     * Stored rather than derived so that renaming a task is possible later and
     * so a list does not have to read every prompt to draw itself.
     */
    title VARCHAR(200) NOT NULL,

    /* What was asked, in full. The first thing the agent is told, and kept
     * here as well as in the session because the session may be deleted and
     * the task is still a record of what was wanted. */
    prompt TEXT NOT NULL,

    /*
     * Who is doing it, and what it thinks with.
     *
     * An agent is the ordinary case: its grants are what the task may reach.
     * A task may also name a model and no agent, which is a worker with no
     * grants at all - it has the three tools every task has and nothing else
     * until somebody approves something. Both are SET NULL rather than CASCADE:
     * a finished task is a record, and deleting the agent that did it should
     * not delete the account of what it did.
     */
    agent_id BIGINT REFERENCES agent (id) ON DELETE SET NULL,
    model_id BIGINT REFERENCES llm_model (id) ON DELETE SET NULL,

    /* QUEUED, RUNNING, WAITING, DONE, FAILED or STOPPED. No CHECK: the enum is
     * enforced where the rows are written, and a constraint here would have to
     * be widened in two schemas every time a value is added. */
    status VARCHAR(16) NOT NULL,

    /*
     * The event log, which is an LLM session and not a table of its own.
     *
     * Everything the task does - what it was asked, every tool it called and
     * what came back, everything it said, every note from the machinery - is
     * written by LlmSessionRecorder into llm_session_event. A second log here
     * would be a second thing to keep in step with the first.
     */
    session_id BIGINT REFERENCES llm_session (id) ON DELETE SET NULL,

    /* The issue this was started from, where something started it from one.
     * Null for a task somebody typed on the Tasks page. It is both the link
     * back and the reason the issue's observers hear about it. */
    issue_id BIGINT REFERENCES workspace_issue (id) ON DELETE SET NULL,

    created_by VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,

    /*
     * What it has spent, and what it may.
     *
     * Two ceilings rather than one, for the reason the retry policy carries a
     * budget beside its attempts: the turns bound how many times the model is
     * asked, and the seconds bound what happens between two of those - a shell
     * command, an MCP server that takes its time - which no count of turns can
     * express. Both are copied onto the row when the task is created, so
     * changing the installation's defaults does not move the goalposts under a
     * task already running.
     *
     * The seconds are *worked* seconds and not wall clock. A task parked
     * waiting for somebody to approve something may sit there for days, and
     * charging that to its budget would mean the answer to "why did this fail"
     * being "you went home".
     */
    turns_spent INT NOT NULL DEFAULT 0,
    worked_seconds BIGINT NOT NULL DEFAULT 0,
    turns_allowed INT NOT NULL,
    seconds_allowed BIGINT NOT NULL,

    /*
     * When a parked task gives up on being answered.
     *
     * Null unless it is waiting. A task that stops for permission and is never
     * answered would otherwise be a workflow held open for ever and a row that
     * says "waiting" for the rest of the installation's life.
     */
    waiting_until TIMESTAMPTZ,

    /* What the agent finally said, on a task that reached an end. */
    outcome TEXT,

    /* Why it stopped, in the words the page shows: "finished", "out of turns",
     * "nobody answered", "stopped by alice". Null while it is still going. */
    ended_because VARCHAR(200)
);

-- How the list opens: this workspace's tasks, newest first.
CREATE INDEX task_workspace_idx ON task (workspace_id, created_at DESC);

-- What still needs somebody, across the installation, for the sweep that gives
-- up on tasks nobody answered.
CREATE INDEX task_waiting_idx ON task (status, waiting_until);

-- Something the agent stopped to ask for.
--
-- Two kinds and one table, because they are one mechanism: the task parks, a
-- person answers, the task carries on with exactly what they said. Permission
-- and a plain question differ only in what the answer is - a grant, or some
-- words - and building them separately would have meant two ways to park and
-- two ways to resume.
CREATE TABLE task_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    task_id BIGINT NOT NULL REFERENCES task (id) ON DELETE CASCADE,

    /* PERMISSION or QUESTION. */
    kind VARCHAR(16) NOT NULL,

    /*
     * What is being asked for, on a permission request: ORKNUX, SHELLS, TOOL,
     * MCP_SERVER, SKILL_CATALOG or MEMORY_CATALOG. These are the grants an
     * agent already has, named the same way, so approving one is the same
     * decision somebody makes on an agent's own page - taken for this task
     * alone.
     *
     * Null on a question.
     */
    capability VARCHAR(20),

    /* Which one, where the capability names one: the tool, the server, the
     * catalog. Null for ORKNUX and SHELLS, which name nothing, and null on a
     * question. */
    subject VARCHAR(200),

    /* The question, or why the agent says it needs the thing. It is what the
     * person reads before deciding, so it is never null. */
    asks TEXT NOT NULL,

    asked_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    /* GRANTED, REFUSED or ANSWERED, and null while it is still waiting. */
    decision VARCHAR(16),

    /* What the person said, on a question. Null on a permission. */
    answer TEXT,

    /* Who decided, always recorded. An approval that cannot say who gave it is
     * not a record of a decision. */
    decided_by VARCHAR(120),
    decided_at TIMESTAMPTZ
);

-- One task's requests, in the order they were made. The id joins the sort for
-- the reason a transcript's does: two rows written in one millisecond need
-- something to tell them apart.
CREATE INDEX task_request_task_idx ON task_request (task_id, asked_at, id);

-- Something a person let this task do that its agent may not.
--
-- On the task and not on the agent, which is the whole of the safety argument.
-- Approving a shell for one afternoon's work must not arm the agent in every
-- chat for ever, and it does not: this row is read only while this task runs
-- and is thrown away with it.
CREATE TABLE task_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    task_id BIGINT NOT NULL REFERENCES task (id) ON DELETE CASCADE,

    /* The request it answers, so the page can show what was asked beside what
     * was given. SET NULL rather than CASCADE: the grant is the decision and
     * outlives the wording of the request. */
    request_id BIGINT REFERENCES task_request (id) ON DELETE SET NULL,

    /* The same vocabulary task_request.capability uses. */
    capability VARCHAR(20) NOT NULL,
    subject VARCHAR(200),

    granted_by VARCHAR(120) NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX task_grant_task_idx ON task_grant (task_id);
