-- What kind of thing an issue is: a bug, a feature, or whatever else a
-- workspace decides it files.
--
-- A table rather than a reserved label prefix, which is the obvious cheaper
-- answer and does not work. Three things separate the two:
--
--   Cardinality. Labels are a set, and a set cannot say "exactly one". Nothing
--   would stop `type:bug` and `type:feature` sitting on the same issue, so
--   every reader - the list, the filter, the tools, a person - would have to
--   decide for itself what an issue with two types is, and they would decide
--   differently.
--
--   Lifetime. A label exists because an issue carries it: the list is
--   `select distinct label`, so taking the last issue off one deletes it and
--   there is nothing to administer before the first issue is filed. The whole
--   of what was asked for is a page where a workspace decides which types it
--   has, which means the type has to exist while nothing carries it.
--
--   A name that can be changed. Renaming a label means rewriting every row that
--   holds the string; renaming a type is one update, and the issues follow.
--
-- Labels stay exactly as they were. They are what a workspace says *about* an
-- issue, as many things at once as it likes; this is what the issue *is*.
CREATE TABLE workspace_issue_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    -- As long as a label, because they are read side by side and a type that
    -- could be longer would be a chip that wraps where the ones beside it do not.
    name VARCHAR(60) NOT NULL
);

-- One `bug` per workspace however it is capitalised. Two types that differ only
-- in case are two rows a person reading the list cannot tell apart, and one of
-- them would collect issues by accident.
CREATE UNIQUE INDEX workspace_issue_type_name_key ON workspace_issue_type (workspace_id, lower(name));

-- Null, and left null for every issue that already exists.
--
-- Untyped is a real state and not a gap waiting to be filled: a default would
-- retroactively claim that every issue filed before today was a bug, which is a
-- record saying something nobody ever said. The list can be asked for the
-- untyped ones and the page shows the word.
--
-- ON DELETE SET NULL is for the one deletion the product actually allows here:
-- deleting the whole workspace, where the issues are going too and the order
-- the two cascades happen in must not matter - SQLite enforces a foreign key
-- the moment the row goes, so a RESTRICT here would refuse to delete a
-- workspace on the engine orknux-one ships with and delete it happily on
-- Postgres. Deleting a type that issues carry is refused above this, in words,
-- naming how many carry it.
ALTER TABLE workspace_issue ADD COLUMN type_id BIGINT REFERENCES workspace_issue_type (id) ON DELETE SET NULL;

CREATE INDEX workspace_issue_type_idx ON workspace_issue (workspace_id, type_id);

-- Two to begin with, in every workspace that already has one.
--
-- The catalogue and not the issues: a workspace opening its tracker tomorrow
-- finds `bug` and `feature` ready to be chosen, and not one existing issue has
-- been told what it is. New workspaces are seeded the same two in code, when
-- they are created, so there is one answer rather than one per engine.
INSERT INTO workspace_issue_type (workspace_id, name) SELECT id, 'bug' FROM workspace;
INSERT INTO workspace_issue_type (workspace_id, name) SELECT id, 'feature' FROM workspace;
