-- What a reasoning model thought on its way to an answer, kept beside the
-- answer it belongs to.
--
-- Issue #271 asked for chain of thought in the chat. It was first built to live
-- only as long as the turn: shown on the answer being written and gone on
-- reload, following what #227 settled for the cost of a turn. That was rejected,
-- and the rejection is right. A cost is a number nobody re-reads; thinking is
-- content. An answer whose reasoning vanishes when the page reloads is an
-- answer nobody can go back and check, which is most of the reason for showing
-- it at all.
--
-- **Why it is not in the session, which is where the tool calls are.**
-- An agent's lookups survive a reload because they were already being written
-- to `llm_session_event`, and a chat handed to an agent opens a session of its
-- own to hold them. Thinking cannot ride that road, for two separate reasons
-- and either one alone would be enough. Nothing writes reasoning to that table
-- at all - the recorder keeps what was said and what a tool returned. And a
-- chat with a bare model has no session in the first place: `ChatService`
-- opens one only for an agent, deliberately, because a chat that calls no tools
-- has nothing to record and computing a session key for one bends a rule that
-- otherwise holds for every chat. A bare model is exactly the case this feature
-- is most for - somebody talking to a reasoning model directly - so the road
-- that is closed is closed precisely where it was needed.
--
-- **This is not a messages table, and the rule against one still stands.** It is
-- the same shape and the same argument as `chat_answer_take`, which was settled
-- on the same ground: the conversation lives in `spring_ai_chat_memory` keyed by
-- a conversation id, because a workflow run keys one the same way and every
-- agent in it shares the thread. What is here was deliberately kept *out* of
-- that thread. It is not part of the conversation, it is never put in front of
-- a model, and nothing but the chat screen reads it. Putting it in the thread
-- is not a cheaper way of doing this - it is the bug, because everything that
-- reads the thread would then read the thinking as something the model said.
CREATE TABLE chat_message_thinking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    chat_session_id BIGINT NOT NULL REFERENCES chat_session (id) ON DELETE CASCADE,

    -- Which answer this is the thinking for: its place in the thread, counted
    -- from the start.
    --
    -- A position rather than a message id, for the reason `chat_answer_take`
    -- gives: Spring AI's store gives a message no id at all, it keeps a
    -- conversation, a role, some text and an order. The position holds for the
    -- life of a chat, because the thread is only ever appended to and a
    -- regenerate replaces the last turn in place rather than inserting.
    message_index INTEGER NOT NULL,

    -- Kept whole. What is shown is folded rather than cut, so there is no
    -- length the screen needs this shortened to - and a model's reasoning
    -- truncated in the middle is worse than none, because the part that
    -- explains the answer is usually the end of it.
    content TEXT NOT NULL,

    -- How long the thinking went on for, measured over the reasoning frames
    -- alone rather than over the turn. Nought where it did not arrive as a
    -- stream and there was no duration to measure, which the screen draws as
    -- no time at all rather than as nought seconds.
    millis BIGINT NOT NULL DEFAULT 0,

    thought_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One answer has one thinking. A regenerate replaces the answer at this
    -- position, so it replaces the thinking too rather than leaving the old
    -- one under a new answer - which would be the same lie as a lookup drawn
    -- under an answer that did not make it.
    CONSTRAINT chat_message_thinking_at_uq UNIQUE (chat_session_id, message_index)
);
