-- Something a person said to a task while it was working.
--
-- The one thing a task could not be told until now. A parked task is answered
-- through task_request, which is the agent asking and somebody replying; this
-- is the other direction and nobody asked for it - the work is going, somebody
-- reads what it is doing, and what they want is to change it without stopping
-- it and starting again.
--
-- ## Why this is not a second transcript
--
-- It is a doorstep, not a record. A message lives here only until the loop
-- picks it up: at the top of its next turn the task writes the words into its
-- LLM session as a turn from the person who typed them, exactly the way
-- TaskService already writes an answer to a question, and stamps delivered_at
-- here. From that moment the session is the account of what was said, and this
-- row is a receipt saying when it got there. The transcript still has one home.
--
-- The reason it cannot simply be written into the session at the moment the
-- person presses send is ordering. A turn is minutes long and the agent's own
-- answer is written when the turn ends, so a message dropped into the session
-- mid-turn lands *before* an answer that was composed without it - and the next
-- turn reads a conversation in which the agent appears to have already replied
-- to something it never saw. Held here and handed over at a turn boundary, the
-- transcript says what actually happened in the order it happened.
--
-- ## How it reaches a run that is already going
--
-- It does not. The run comes and reads it, which is the same answer the rest of
-- this feature gives: a task's whole state is its row and its session, the loop
-- reads them at the top of every turn, and there is no signal, no queue and no
-- second way for a task to learn something. That is what makes this work
-- identically on the inline engine and on Temporal, and what makes a message
-- sent to a task whose process died a moment later still arrive - to whichever
-- process picks the task up.
CREATE TABLE task_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    task_id BIGINT NOT NULL REFERENCES task (id) ON DELETE CASCADE,

    /* Whoever typed it, by username. It is written into the transcript under
     * this name, so the agent's account of the work says who redirected it. */
    said_by VARCHAR(120) NOT NULL,

    /* What they said, in full and unedited. */
    body TEXT NOT NULL,

    sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    /*
     * When the loop put it in front of the agent, and null until it did.
     *
     * The field the page needs to be honest with. A message typed while the
     * model is mid-turn has not been read yet and saying that it has would be a
     * lie the person acts on; a message typed at a task that finishes before
     * its next turn is never read at all, and the row is what says so rather
     * than the words quietly disappearing.
     */
    delivered_at TIMESTAMPTZ
);

-- One task's messages, oldest first. The id joins the sort for the reason a
-- transcript's does: two rows written in one millisecond need something to tell
-- them apart.
CREATE INDEX task_message_task_idx ON task_message (task_id, sent_at, id);
