-- A picture a task drew, so that a task can produce one at all.
--
-- V206 gave the installation a model that draws and gave a chat the button that
-- asks it. A task had no way to reach it: the only thing an agent working alone
-- could produce was prose, so "make me a diagram of this" came back as a
-- description of the diagram. This is the other end of the same feature.
--
-- A table of its own rather than a row on chat_attachment, and the reason is
-- what the column below says: nothing uploads a file to a task. Every row here
-- is something an agent drew, and the description it was drawn from is part of
-- the record - which is a column chat_attachment has no business growing for the
-- sake of a caller that is not a chat. What the two do share is the storage,
-- the size limit and the switch that turns them off, because those are the
-- installation's answer and not this feature's.
CREATE TABLE task_picture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /* Whose it is. CASCADE, because a picture is part of what the task
     * produced: keeping it after the task has been thrown away would leave a
     * file nothing can name and nothing can reach. */
    task_id BIGINT NOT NULL REFERENCES task (id) ON DELETE CASCADE,

    /*
     * The workspace, on the row rather than read back through the task.
     *
     * It is what decides who may open the picture, and it is how the bytes are
     * filed - one directory per workspace, which is the promise the storage
     * makes. The same reasoning chat_attachment and workspace_issue_attachment
     * both wrote down.
     */
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    /* What was asked for, which is the picture's alt text and half of what
     * makes a list of them readable. A picture whose description is gone is a
     * thumbnail somebody has to open to identify. */
    prompt TEXT NOT NULL,

    /* What a download names it, built from the description. */
    filename VARCHAR(255) NOT NULL,

    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,

    /* Where the bytes are, as the storage that wrote them understands it.
     * Never sent to a screen: a path is the sort of thing that invites
     * somebody to ask for a different one. */
    location VARCHAR(1000) NOT NULL,

    drawn_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One task's pictures, in the order they were drawn, which is the order the
-- outcome shows them in. The id joins the sort for the reason a transcript's
-- does: two rows written in one millisecond need something to tell them apart.
CREATE INDEX task_picture_task_idx ON task_picture (task_id, drawn_at, id);
