-- An image node draws a picture from a prompt, with one of the workspace's image
-- models. The model is picked on the node itself, like an agent node picks an
-- agent, so the node carries its id; the run's own copy travels onto the step,
-- like every other id a node instances. Issue #333.
ALTER TABLE workflow_node ADD COLUMN image_model_id BIGINT;
ALTER TABLE execution_step ADD COLUMN image_model_id BIGINT;

-- The node kinds were listed without it, so an image node would be accepted by
-- the application and refused here. Widened on both, because unlike a SESSION
-- node an image node is a step: it runs, and a run records it.
ALTER TABLE workflow_node DROP CONSTRAINT ck_workflow_node_kind;
ALTER TABLE workflow_node ADD CONSTRAINT ck_workflow_node_kind CHECK (
    kind IN ('TRIGGER', 'AGENT', 'ACTION', 'CONDITION', 'OBJECT', 'SESSION', 'IMAGE')
);

ALTER TABLE execution_step DROP CONSTRAINT ck_execution_step_kind;
ALTER TABLE execution_step ADD CONSTRAINT ck_execution_step_kind CHECK (
    kind IN ('TRIGGER', 'AGENT', 'ACTION', 'CONDITION', 'OBJECT', 'IMAGE')
);

-- A picture an image node drew, kept with the run that drew it. The twin of
-- task_picture: the row is the record and the bytes are filed by the same
-- storage, and what it holds that a task's does not is which step drew it, so
-- the run graph can show a preview under that node.
CREATE TABLE execution_picture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /* The run it belongs to. CASCADE, because a picture is part of what the run
     * produced: keeping it after the run is swept would leave a file nothing can
     * name and nothing can reach. */
    execution_id BIGINT NOT NULL REFERENCES workflow_execution (id) ON DELETE CASCADE,

    /* Which step drew it, so the graph shows it under the right node. */
    node_key VARCHAR(64) NOT NULL,

    /* The workspace, on the row rather than read back through the run: it decides
     * who may open the picture, and it is how the bytes are filed. */
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    /* What was asked for, which is the picture's alt text. */
    prompt TEXT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,

    /* Where the bytes are, as the storage that wrote them understands it. */
    location VARCHAR(1000) NOT NULL,

    drawn_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One run's pictures, in the order they were drawn. The id joins the sort so two
-- rows written in one millisecond have something to tell them apart.
CREATE INDEX execution_picture_execution_idx ON execution_picture (execution_id, drawn_at, id);
