-- A condition is a question a team asks about what a run is carrying, defined
-- once and used from several places: a wait that holds until it holds, and a
-- condition node that stops a run when it does not.

CREATE TABLE workflow_condition
(
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id  BIGINT       NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    name     VARCHAR(120) NOT NULL,
    -- What it asks about: a service's event, the clock, or other conditions.
    type     VARCHAR(16)  NOT NULL,
    -- Which part of the event, and how it is tested. Null for a composite.
    property VARCHAR(32),
    -- `check` is reserved in SQL.
    check_by VARCHAR(16),
    -- Answers the opposite. "Is external" is "is a teammate", negated.
    negate   BOOLEAN      NOT NULL DEFAULT FALSE,
    -- For a FUNCTION condition: the team's JavaScript that answers it. It has
    -- to return a boolean, which is checked when the condition is saved.
    function_id BIGINT REFERENCES workflow_function (id) ON DELETE SET NULL,
    CONSTRAINT uk_workflow_condition_name UNIQUE (team_id, name),
    CONSTRAINT ck_workflow_condition_type
        CHECK (type IN ('SLACK', 'JIRA', 'TIME', 'FUNCTION', 'ANY_OF', 'ALL_OF')),
    CONSTRAINT ck_workflow_condition_shape CHECK (
        (type IN ('ANY_OF', 'ALL_OF') AND property IS NULL AND check_by IS NULL)
            OR (type = 'FUNCTION' AND function_id IS NOT NULL AND property IS NULL AND check_by IS NULL)
            OR (type IN ('SLACK', 'JIRA', 'TIME') AND property IS NOT NULL AND check_by IS NOT NULL)
        )
);

-- What the check compares against: the list, the pattern, the two ends of a range.
CREATE TABLE workflow_condition_value
(
    condition_id BIGINT       NOT NULL REFERENCES workflow_condition (id) ON DELETE CASCADE,
    position     INTEGER      NOT NULL,
    value        VARCHAR(500) NOT NULL,
    PRIMARY KEY (condition_id, position)
);

-- The conditions a composite is made of.
CREATE TABLE workflow_condition_member
(
    condition_id BIGINT  NOT NULL REFERENCES workflow_condition (id) ON DELETE CASCADE,
    position     INTEGER NOT NULL,
    member_id    BIGINT  NOT NULL REFERENCES workflow_condition (id) ON DELETE CASCADE,
    PRIMARY KEY (condition_id, position)
);

-- A wait can now hold until a condition from the catalogue holds, as well as
-- until an expression written into the action does.
ALTER TABLE workflow_action
    ADD COLUMN condition_id BIGINT REFERENCES workflow_condition (id) ON DELETE SET NULL;

-- What was CONDITION is an expression written in the action, which is what
-- INLINE_CONDITION now says; CONDITION means one from the catalogue.
UPDATE workflow_action
SET subtype = 'INLINE_CONDITION'
WHERE subtype = 'CONDITION';

ALTER TABLE workflow_action
    DROP CONSTRAINT ck_workflow_action_subtype;
ALTER TABLE workflow_action
    ADD CONSTRAINT ck_workflow_action_subtype
        CHECK (subtype IN ('OUTGOING_CONNECTION', 'HTTP_REQUEST', 'FUNCTION', 'INLINE_CONDITION', 'CONDITION', 'TIME'));

ALTER TABLE workflow_action
    DROP CONSTRAINT ck_workflow_action_shape;
ALTER TABLE workflow_action
    ADD CONSTRAINT ck_workflow_action_shape CHECK (
        (type = 'EXECUTE' AND subtype = 'OUTGOING_CONNECTION' AND connection_id IS NOT NULL)
            OR (type = 'EXECUTE' AND subtype = 'HTTP_REQUEST' AND url IS NOT NULL)
            OR (type = 'EXECUTE' AND subtype = 'FUNCTION' AND function_id IS NOT NULL)
            OR (type = 'WAIT' AND subtype = 'INLINE_CONDITION' AND condition_expression IS NOT NULL)
            OR (type = 'WAIT' AND subtype = 'CONDITION' AND condition_id IS NOT NULL)
            OR (type = 'WAIT' AND subtype = 'TIME' AND duration_seconds IS NOT NULL)
        );

-- A condition node asks one of the catalogue's questions of the run it is in.
ALTER TABLE workflow_node
    ADD COLUMN condition_id BIGINT REFERENCES workflow_condition (id) ON DELETE SET NULL;

ALTER TABLE workflow_node
    DROP CONSTRAINT ck_workflow_node_kind;
ALTER TABLE workflow_node
    ADD CONSTRAINT ck_workflow_node_kind
        CHECK (kind IN ('TRIGGER', 'AGENT', 'ACTION', 'CONDITION', 'DATA_TASK', 'PUBLISH_TASK'));

ALTER TABLE execution_step
    ADD COLUMN condition_id BIGINT;

ALTER TABLE execution_step
    DROP CONSTRAINT ck_execution_step_kind;
ALTER TABLE execution_step
    ADD CONSTRAINT ck_execution_step_kind
        CHECK (kind IN ('TRIGGER', 'AGENT', 'ACTION', 'CONDITION', 'DATA_TASK', 'PUBLISH_TASK'));

CREATE INDEX idx_workflow_condition_team ON workflow_condition (team_id);
CREATE INDEX idx_workflow_node_condition ON workflow_node (condition_id) WHERE condition_id IS NOT NULL;
