-- What an agent is given to work with.
--
-- A tool is JavaScript the agent may call while it runs; a skill is markdown
-- that tells it how to go about something. Both belong to a team, both can be
-- turned off without being deleted, and both record who last touched them,
-- because the screens show it beside the content.
--
-- A tool is not a workflow function. A function is called by an action node at
-- a point the graph decides; a tool is offered to an agent, which calls it if
-- it judges that it should. Same sandbox, different caller — so they are
-- separate tables rather than one with a flag.

CREATE TABLE agent_tool
(
    id               BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id          BIGINT                   NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    name             VARCHAR(120)             NOT NULL,
    description      VARCHAR(500),
    -- A module whose default export is the tool, run in the same sandbox a
    -- function runs in, so what is stored is only ever text.
    source           TEXT                     NOT NULL,
    enabled          BOOLEAN                  NOT NULL DEFAULT TRUE,
    last_modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_modified_by VARCHAR(120)             NOT NULL,
    CONSTRAINT uk_agent_tool_name UNIQUE (team_id, name)
);

CREATE INDEX idx_agent_tool_team ON agent_tool (team_id);

CREATE TABLE agent_skill
(
    id               BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id          BIGINT                   NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    name             VARCHAR(120)             NOT NULL,
    description      VARCHAR(500),
    -- Markdown, opening with a frontmatter block naming and describing it.
    content          TEXT                     NOT NULL,
    enabled          BOOLEAN                  NOT NULL DEFAULT TRUE,
    last_modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_modified_by VARCHAR(120)             NOT NULL,
    CONSTRAINT uk_agent_skill_name UNIQUE (team_id, name)
);

CREATE INDEX idx_agent_skill_team ON agent_skill (team_id);
