-- Chat: a conversation somebody holds with a model, and the messages in it.
--
-- The messages are not ours. They live in Spring AI's chat memory store, keyed
-- by a conversation id, which is the whole point of using it: the history a
-- chat keeps is the same shape of history a workflow run will keep, so when an
-- execution becomes a conversation every agent in that run shares one thread
-- rather than each keeping its own.
--
-- So this table holds what Spring AI does not: who owns the conversation, what
-- it is called, which model answers it, and whether it is pinned. The link
-- between the two is `conversation_id`.

CREATE TABLE chat_session
(
    id              BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id    BIGINT                   NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    -- What Spring AI keys its messages by. A UUID, because that column is
    -- VARCHAR(36) in the store and a UUID is exactly that.
    conversation_id VARCHAR(36)              NOT NULL,
    title           VARCHAR(200)             NOT NULL,
    -- The LDAP uid of whoever started it: the sidebar says USER CHATS.
    user_id         VARCHAR(120)             NOT NULL,
    -- Which model answers. Null once the model it named has been removed, which
    -- leaves the history readable and the chat unable to go on until another is
    -- chosen.
    model_id        BIGINT                   REFERENCES llm_model (id) ON DELETE SET NULL,
    pinned          BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Ordering for RECENT, and what a new chat has none of.
    last_message_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_chat_session_conversation UNIQUE (conversation_id)
);

CREATE INDEX idx_chat_session_owner ON chat_session (workspace_id, user_id, last_message_at DESC);

-- Spring AI's own table, created here rather than by its schema initializer:
-- Flyway owns this schema, and one history of it is the rule. Kept exactly as
-- `schema-postgresql.sql` in spring-ai-model-chat-memory-repository-jdbc
-- declares it, so the repository finds what it expects.
CREATE TABLE IF NOT EXISTS SPRING_AI_CHAT_MEMORY
(
    conversation_id VARCHAR(36) NOT NULL,
    content         TEXT        NOT NULL,
    type            VARCHAR(10) NOT NULL CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')),
    "timestamp"     TIMESTAMP   NOT NULL,
    sequence_id     BIGINT      NOT NULL
);

CREATE INDEX IF NOT EXISTS SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_IDX
    ON SPRING_AI_CHAT_MEMORY (conversation_id, "timestamp");

CREATE INDEX IF NOT EXISTS SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_SEQUENCE_ID_IDX
    ON SPRING_AI_CHAT_MEMORY (conversation_id, sequence_id);
