-- What a trigger did, every time it was asked to do anything.
--
-- A trigger that starts nothing is silent in every existing screen: the
-- executions list only shows runs that began, and a definition nobody instances,
-- a condition that turned an event down, or an event Slack never sent all look
-- identical from outside — nothing happened, and no way to tell which nothing.
--
-- Kept per definition rather than per run, because the interesting cases are the
-- ones where no run exists.
CREATE TABLE trigger_firing
(
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_id   BIGINT      NOT NULL REFERENCES workflow_trigger (id) ON DELETE CASCADE,
    workspace_id BIGINT      NOT NULL,
    at           TIMESTAMPTZ NOT NULL,
    -- STARTED, NO_INSTANCE, CONDITION_DID_NOT_HOLD, UNDECIDED, FAILED.
    outcome      VARCHAR(32) NOT NULL,
    -- What to say on the screen, in the words the screen uses.
    detail       TEXT,
    runs_started INTEGER     NOT NULL DEFAULT 0
);

-- The log is always read newest first, for one trigger.
CREATE INDEX idx_trigger_firing_trigger ON trigger_firing (trigger_id, at DESC);
