-- A workflow definition exists on its own; teams get an assignment to it.
CREATE TABLE workflow
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_workflow_name UNIQUE (name)
);

-- Removing an assignment leaves the workflow definition in place.
CREATE TABLE team_workflow
(
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT  NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    workflow_id BIGINT  NOT NULL REFERENCES workflow (id) ON DELETE CASCADE,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_team_workflow UNIQUE (team_id, workflow_id)
);

CREATE INDEX idx_team_workflow_team_id ON team_workflow (team_id);
