-- Named values a workspace keeps, and the two things that read them.
--
-- A function that checks a signature needs the secret it checks against, and
-- until now the only places to put one were the source itself — where it is
-- readable by anyone who can open the editor, and copied into every function
-- that needs it — or a node's parameter, where it travels through a graph in
-- plain sight.
--
-- A variable is that value, named once and stored the way every other credential
-- here is: encrypted at rest, and never sent back to a screen. What a screen
-- gets is the name, the type, and whether a value has been set.
-- A folder of variables.
--
-- Its own table rather than a label, for the reason a skill catalog is one: the
-- screen lists vaults beside the variables of the one selected, so a vault is a
-- thing that exists, and has a count worth showing, before anything is in it.
CREATE TABLE variable_vault (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by VARCHAR(120) NOT NULL DEFAULT '',
    CONSTRAINT uk_variable_vault_name UNIQUE (workspace_id, name)
);

CREATE INDEX idx_variable_vault_workspace ON variable_vault (workspace_id);

CREATE TABLE workspace_variable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    -- Which vault holds it. Required, so every variable is somewhere: a list
    -- that can be filtered by vault and a set of variables belonging to none
    -- would be two ways of finding things.
    vault_id BIGINT NOT NULL REFERENCES variable_vault (id) ON DELETE RESTRICT,
    name VARCHAR(64) NOT NULL,
    -- Scalars only. An object would be a shape, and shapes are what the object
    -- catalogue is for; a variable is one value a function is handed.
    type VARCHAR(16) NOT NULL,
    -- Same column shape as every other secret: the ciphertext is longer than
    -- what was typed, and the format is `orkx1:iv:ct`.
    value VARCHAR(4096),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_by VARCHAR(120) NOT NULL DEFAULT '',
    -- Unique within the vault, the way a file is unique within a folder. Two
    -- vaults may each hold a `signing_secret` — that is what having vaults is
    -- for — and a function taking both as external parameters is refused where
    -- that is decided, since two arguments of one name is a question nobody
    -- should have to answer.
    CONSTRAINT uk_workspace_variable_name UNIQUE (vault_id, name),
    CONSTRAINT ck_workspace_variable_type CHECK (type IN ('STRING', 'NUMBER', 'BOOLEAN'))
);

CREATE INDEX idx_workspace_variable_workspace ON workspace_variable (workspace_id);
CREATE INDEX idx_workspace_variable_vault ON workspace_variable (vault_id);

-- What a function is handed on top of what a node passes it.
--
-- A declared parameter is the caller's to fill; an external one is not — it is
-- the workspace's, and the function receives it whether it is called from a
-- node, from a condition, or by a webhook checking who is calling. Kept in
-- order, because they arrive as arguments and arguments have positions.
CREATE TABLE workflow_function_external (
    function_id BIGINT NOT NULL REFERENCES workflow_function (id) ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES workspace_variable (id) ON DELETE RESTRICT,
    position INT NOT NULL,
    PRIMARY KEY (function_id, position)
);

CREATE INDEX idx_workflow_function_external_variable ON workflow_function_external (variable_id);

-- How a webhook decides whether the caller is allowed to start anything.
--
-- NONE is what every webhook has been until now: knowing the path and the shape
-- is enough. FUNCTION hands the request to one of the workspace's functions and
-- believes what it answers — which is how a signature gets checked against a
-- secret nobody has to paste into a graph.
ALTER TABLE workflow_trigger
    ADD COLUMN auth_type VARCHAR(16) NOT NULL DEFAULT 'NONE',
    ADD COLUMN auth_function_id BIGINT REFERENCES workflow_function (id);

ALTER TABLE workflow_trigger
    ADD CONSTRAINT ck_workflow_trigger_auth CHECK (
        auth_type IN ('NONE', 'FUNCTION')
        AND (auth_type <> 'FUNCTION' OR auth_function_id IS NOT NULL)
    );
