-- A plugin loaded into this installation.
--
-- Installation-level rather than per-workspace: a plugin is something an
-- operator loads once for everyone. What it may then do, and inside which
-- workspace, is a separate question this table deliberately does not answer —
-- there is nothing here about capabilities, grants or entry points, because
-- none of that is decided yet.
--
-- The source lives on the row rather than on disk, which is the opposite of what
-- attachments do. An attachment is arbitrary bytes of arbitrary size, so it
-- belongs wherever storage was configured; a plugin is text, small, and the
-- thing itself rather than a document about something else. On the row it is
-- backed up with the record, cannot be orphaned by a failed delete, and needs no
-- storage to be configured before anything works.
CREATE TABLE plugin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- What it is called on the screen. Taken from the filename it arrived as.
    name VARCHAR(200) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    source TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    -- Which plugin API the plugin says it was written against. Read from the
    -- plugin itself while it is being uploaded; one this server does not know is
    -- refused rather than stored, so every row here is a version that can run.
    api_version INT NOT NULL,
    -- Identifies the exact text, so an unchanged re-upload is recognisable and
    -- two plugins that are the same file can be told apart from two that merely
    -- share a name.
    sha256 VARCHAR(64) NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    uploaded_by VARCHAR(120) NOT NULL DEFAULT ''
);

-- One plugin per name. Uploading the same name again replaces what is loaded,
-- which is what iterating on a plugin looks like; a name is how everything else
-- will come to refer to it.
CREATE UNIQUE INDEX idx_plugin_name ON plugin (name);
