-- Files attached to an issue, and to the comments on it.
--
-- The same arrangement chat_attachment already uses, because the storage is the
-- same storage: the row is the record and the bytes are wherever the configured
-- attachment storage put them, under one directory per workspace. A second
-- table rather than a column on chat_attachment - what a file hangs off differs
-- (a chat, an issue, a comment), and a table whose foreign keys are all nullable
-- because only one of them ever applies is a table that cannot be read.
--
-- The workspace is on the row rather than reached through the issue, for the
-- reason it is on the chat's: it decides who may read the file, and it is how
-- the bytes are filed on disk.
CREATE TABLE workspace_issue_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    /*
     * Null while the issue it is going on has not been filed yet.
     *
     * A file goes up while the report is still being written - the upload is
     * what takes the time, and doing it on save would mean pressing "File
     * Issue" and waiting - so there is a moment where the bytes exist and the
     * issue does not.
     */
    issue_id BIGINT REFERENCES workspace_issue (id) ON DELETE CASCADE,

    /*
     * The comment it came with, or null when it is on the issue itself.
     *
     * Both columns rather than one: a comment's attachment belongs to its issue
     * as well, so deleting the issue takes it either way, and the issue's own
     * files can be listed without walking every comment.
     */
    comment_id BIGINT REFERENCES workspace_issue_comment (id) ON DELETE CASCADE,

    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,

    -- Where the bytes are, as the storage that wrote them understands it: a
    -- path for a filesystem, a key for anything else. Text rather than a path
    -- column, so object storage can arrive as a class rather than as a
    -- migration of everything anybody has uploaded.
    location VARCHAR(1000) NOT NULL,

    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Who attached it, and so the only person who may take it off again. A name
    -- rather than a foreign key, like the reporter of an issue: whoever
    -- attached a file stays whoever attached it after their row is gone.
    uploaded_by VARCHAR(120) NOT NULL DEFAULT ''
);

CREATE INDEX workspace_issue_attachment_issue_idx ON workspace_issue_attachment (issue_id, uploaded_at);
CREATE INDEX workspace_issue_attachment_comment_idx ON workspace_issue_attachment (comment_id);
CREATE INDEX workspace_issue_attachment_workspace_idx ON workspace_issue_attachment (workspace_id);
