-- Web addresses hung on an issue.
--
-- Half of what a bug report points at lives somewhere else - the pull request
-- that caused it, the dashboard that showed it, the page that will not load -
-- and pasting those into the description buries them in prose. Their own rows
-- so they can be listed, counted and taken off one at a time.
--
-- Beside workspace_issue_attachment rather than inside it: what is stored is an
-- address and nothing is on the disk, so none of the columns that make an
-- attachment an attachment - the size, the type, where the bytes went - mean
-- anything here.
CREATE TABLE workspace_issue_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Not null, unlike an attachment's issue: an address is typed rather than
    -- uploaded, so there is no moment where it exists and the issue does not.
    -- Its workspace is the issue's, and is read through it, because there are
    -- no bytes to file anywhere.
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,

    -- Long enough for the addresses people actually paste, which are mostly a
    -- tracker's or a dashboard's and carry a query string.
    url VARCHAR(2000) NOT NULL,

    -- What whoever added it called it, or null when they let the address speak
    -- for itself. Optional because a GitHub address already says what it is.
    title VARCHAR(200),

    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Who added it, and so the only person who may take it off again. A name
    -- rather than a foreign key, like the reporter of an issue: whoever added a
    -- link stays whoever added it after their row is gone.
    added_by VARCHAR(120) NOT NULL DEFAULT ''
);

-- Read one issue at a time, oldest first, which is the order they were added
-- in and the order they are shown in.
CREATE INDEX workspace_issue_link_issue_idx ON workspace_issue_link (issue_id, added_at);
