-- Getting back in after forgetting a password.
--
-- Until now the only way was to find an administrator and ask them to type a new
-- one into the user screen, which is a poor answer at a weekend and a worse one
-- for the administrator who has forgotten theirs.
--
-- A row here is a link that has been mailed out and not yet used. It holds the
-- hash of the token and never the token itself, exactly as `app_user_token`
-- does: a table that could give the secret back would be a password written
-- down, and this one would be a password written down for somebody else.
--
-- Only ever for an INTERNAL user with a password already. An external user's
-- password belongs to the directory that keeps it, and an internal identity that
-- has never had one is not an account to get back into - handing it a password by
-- mail would turn something that could only be assigned work into something that
-- can sign in.
CREATE TABLE password_reset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,

    /* SHA-256 of the token in the link, hex. The token is 32 random bytes, so a
       slow hash buys nothing here that its own entropy has not already bought -
       the same argument app_user_token makes for the same shape of secret. */
    token_hash VARCHAR(64) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    /* Written when the link is made rather than worked out when it is followed,
       so shortening the configured lifetime cannot reach back and extend a link
       that is already in somebody's inbox. */
    expires_at TIMESTAMPTZ NOT NULL,

    /* Set the moment the link is used, and the row is kept afterwards. A used
       link that is followed twice - the second time by whoever else has read the
       mailbox since - should be told it has been used, and a row that vanished
       on use would be indistinguishable from one that never existed. */
    used_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX password_reset_hash_key ON password_reset (token_hash);
CREATE INDEX password_reset_user_idx ON password_reset (user_id);
