-- What happened to an issue, kept as a fact about the issue.
--
-- The tracker recorded an issue's life in three places and none of them was a
-- history. The workspace audit log is free text keyed by a workspace, so one
-- issue's lines can only be found by matching "Issue #4" inside a sentence -
-- which finds the wrong issue in a workspace where that number has since been
-- reused, loses everything an issue took with it when it was moved to another
-- workspace, and cannot say what a change was from. The news is written once
-- per person told, so an event nobody was listening for was never written down
-- at all. Comments are the one part that was always kept properly, which is why
-- they are still kept there and read from there rather than copied in here.
--
-- And two of the four things anybody asks a history for were recorded nowhere:
-- nothing anywhere wrote down a label being added or removed, or an issue
-- changing hands. The MCP tools an agent works the tracker through write no
-- audit line at all, so even the parts the audit log did hold had a hole in
-- them exactly where nobody was watching.
--
-- This does not replace the audit log and does not duplicate it. That log
-- answers "what has this workspace done", read in its settings across
-- everything; this answers "why is this issue closed", read on the issue. Where
-- both are worth writing, both are written.
CREATE TABLE workspace_issue_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The row id rather than the number people say. A number is per workspace:
    -- an issue that moves is given a free one where it lands and leaves its old
    -- one for the next issue filed. Keyed by the id, a history moves with its
    -- issue and is deleted with it.
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,

    /*
     * STATUS, LABEL, ASSIGNEE, OBSERVER, or RECORDING for the one line that
     * says where recording began. The two other kinds a reader sees - the issue
     * being opened, and a comment - are read off the issue and its comments,
     * because both are already recorded faithfully and a copy of a comment is a
     * copy that goes stale the moment somebody edits it.
     */
    kind VARCHAR(16) NOT NULL,

    -- Who did it. Never null: a history that cannot name anybody is a rumour.
    actor VARCHAR(120) NOT NULL,

    /*
     * What it was and what it became - the old and new status, the assignee it
     * was taken from and given to, the label removed or added. One label per
     * row rather than a joined list, because any separator is a character a
     * label may contain, and the encoding would be the thing deciding whether
     * "slack, timing" was one label or two long after anybody could ask.
     *
     * An assignee is written as the name it resolved to at the time, like the
     * reporter beside it, because this is a record of something that happened
     * and it stays true after the agent it names has been deleted.
     */
    was TEXT,
    became TEXT,

    at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One issue's story, in order. The id is in the index because a save that swaps
-- three labels writes its rows in the same instant, and a history that reorders
-- itself between two reads is a history nobody trusts.
CREATE INDEX workspace_issue_event_issue_idx ON workspace_issue_event (issue_id, at, id);

-- Where the recording starts, said out loud, for every issue that was already
-- here.
--
-- An issue opened last week whose history begins today would be claiming it had
-- a quiet week, and implying an absence of events is the one thing a record
-- must never do. So each existing issue gets a line saying this is the moment
-- anything began to be written down; everything above it in the tab is what
-- genuinely survived - when it was opened, and what was said on it. An issue
-- filed after this migration has no such line, and needs none.
INSERT INTO workspace_issue_event (issue_id, kind, actor, at)
SELECT id, 'RECORDING', 'system', now() FROM workspace_issue;
