-- A workflow is edited as a graph and published when it is ready.
ALTER TABLE workflow
    ADD COLUMN status VARCHAR(16) NOT NULL DEFAULT 'DRAFT';

ALTER TABLE workflow
    ADD CONSTRAINT ck_workflow_status CHECK (status IN ('DRAFT', 'PUBLISHED'));

CREATE TABLE workflow_node
(
    id             BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id    BIGINT           NOT NULL REFERENCES workflow (id) ON DELETE CASCADE,
    -- Stable within a workflow; what edges refer to.
    node_key       VARCHAR(64)      NOT NULL,
    kind           VARCHAR(16)      NOT NULL,
    name           VARCHAR(255)     NOT NULL,
    description    VARCHAR(500),
    agent_class    VARCHAR(255),
    model_provider VARCHAR(255),
    position_x     DOUBLE PRECISION NOT NULL,
    position_y     DOUBLE PRECISION NOT NULL,
    CONSTRAINT uk_workflow_node UNIQUE (workflow_id, node_key),
    CONSTRAINT ck_workflow_node_kind CHECK (kind IN ('TRIGGER', 'AGENT', 'DATA_TASK', 'PUBLISH_TASK'))
);

CREATE TABLE workflow_edge
(
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT      NOT NULL REFERENCES workflow (id) ON DELETE CASCADE,
    source_key  VARCHAR(64) NOT NULL,
    target_key  VARCHAR(64) NOT NULL,
    CONSTRAINT uk_workflow_edge UNIQUE (workflow_id, source_key, target_key)
);

CREATE INDEX idx_workflow_node_workflow ON workflow_node (workflow_id);
CREATE INDEX idx_workflow_edge_workflow ON workflow_edge (workflow_id);
