-- What a run did: the graph as it ran, one row per node, and the log it produced.
-- A run keeps its own copy of the nodes and edges, so the detail still shows what
-- happened after the workflow is edited.

ALTER TABLE workflow_execution
    ADD COLUMN agent_name VARCHAR(255);

CREATE TABLE execution_step
(
    id           BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT           NOT NULL REFERENCES workflow_execution (id) ON DELETE CASCADE,
    -- Matches the workflow node it came from, and what edges and logs refer to.
    node_key     VARCHAR(64)      NOT NULL,
    kind         VARCHAR(16)      NOT NULL,
    name         VARCHAR(255)     NOT NULL,
    description  VARCHAR(500),
    status       VARCHAR(16)      NOT NULL,
    position_x   DOUBLE PRECISION NOT NULL,
    position_y   DOUBLE PRECISION NOT NULL,
    step_order   INT              NOT NULL,
    started_at   TIMESTAMP WITH TIME ZONE,
    finished_at  TIMESTAMP WITH TIME ZONE,
    -- What the step was handed and what it produced, as the engine recorded it.
    input        TEXT,
    output       TEXT,
    error        VARCHAR(1000),
    CONSTRAINT uk_execution_step UNIQUE (execution_id, node_key),
    CONSTRAINT ck_execution_step_kind CHECK (kind IN ('TRIGGER', 'AGENT', 'DATA_TASK', 'PUBLISH_TASK')),
    CONSTRAINT ck_execution_step_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED'))
);

CREATE INDEX idx_execution_step_execution ON execution_step (execution_id, step_order);

CREATE TABLE execution_edge
(
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT      NOT NULL REFERENCES workflow_execution (id) ON DELETE CASCADE,
    source_key   VARCHAR(64) NOT NULL,
    target_key   VARCHAR(64) NOT NULL,
    CONSTRAINT uk_execution_edge UNIQUE (execution_id, source_key, target_key)
);

CREATE INDEX idx_execution_edge_execution ON execution_edge (execution_id);

CREATE TABLE execution_log
(
    id           BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT                   NOT NULL REFERENCES workflow_execution (id) ON DELETE CASCADE,
    -- Null for lines about the run itself rather than one step.
    node_key     VARCHAR(64),
    logged_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    level        VARCHAR(16)              NOT NULL,
    message      VARCHAR(2000)            NOT NULL,
    -- Keeps lines logged in the same instant in the order they happened.
    sequence_no  INT                      NOT NULL,
    CONSTRAINT ck_execution_log_level CHECK (level IN ('INFO', 'SUCCESS', 'ERROR'))
);

CREATE INDEX idx_execution_log_execution ON execution_log (execution_id, sequence_no);
