-- The connection module's tables: organization-wide default connections, the
-- copies teams hold with their own credentials, and the MCP servers a team
-- talks to. Folded back in from gyloli-connector, which is why they arrive
-- after the migrations that dropped an earlier copy of them.
--
-- team_id is a plain column: the module owns these tables and the team table
-- belongs to another module, so there is no foreign key across that line and
-- no cascade behind a delete — TeamLifecycleService is told instead.

CREATE TABLE connection
(
    id   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)  NOT NULL,
    type VARCHAR(16)   NOT NULL,
    url  VARCHAR(1000) NOT NULL,
    CONSTRAINT uk_connection_name UNIQUE (name),
    CONSTRAINT ck_connection_type CHECK (type IN ('SLACK', 'GITHUB', 'JIRA', 'TEAMS', 'WEBHOOK'))
);

-- A connection as one team sees it. Rows provisioned from a default keep the
-- reference so edits to the default reach them; connection_id is null for a
-- connection the team added itself.
CREATE TABLE team_connection
(
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id            BIGINT        NOT NULL,
    connection_id      BIGINT        REFERENCES connection (id) ON DELETE SET NULL,
    name               VARCHAR(255)  NOT NULL,
    type               VARCHAR(16)   NOT NULL,
    url                VARCHAR(1000) NOT NULL,
    -- The team's own endpoint, used instead of url when set.
    url_override       VARCHAR(1000),
    auth_type          VARCHAR(16)   NOT NULL DEFAULT 'NONE',
    -- Credentials the team configured; a connection counts as connected once set.
    secret             VARCHAR(1000),
    -- Whether a connection works is checked, not assumed: the outcome of the
    -- last probe is kept so the team screen can report it.
    last_check_status  VARCHAR(16),
    last_check_message VARCHAR(500),
    last_checked_at    TIMESTAMPTZ,
    CONSTRAINT uk_team_connection_name UNIQUE (team_id, name),
    CONSTRAINT ck_team_connection_type CHECK (type IN ('SLACK', 'GITHUB', 'JIRA', 'TEAMS', 'WEBHOOK')),
    CONSTRAINT ck_team_connection_auth CHECK (auth_type IN ('NONE', 'API_KEY', 'BEARER_TOKEN', 'BASIC')),
    CONSTRAINT ck_team_connection_check
        CHECK (last_check_status IS NULL OR last_check_status IN ('CONNECTED', 'FAILED'))
);

CREATE INDEX idx_team_connection_team_id ON team_connection (team_id);

CREATE TABLE team_connection_header
(
    team_connection_id BIGINT        NOT NULL REFERENCES team_connection (id) ON DELETE CASCADE,
    position           INT           NOT NULL,
    name               VARCHAR(255)  NOT NULL,
    value              VARCHAR(1000) NOT NULL,
    PRIMARY KEY (team_connection_id, position)
);

CREATE TABLE mcp_server
(
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id   BIGINT        NOT NULL,
    name      VARCHAR(255)  NOT NULL,
    address   VARCHAR(1000) NOT NULL,
    auth_type VARCHAR(16)   NOT NULL DEFAULT 'NONE',
    secret    VARCHAR(1000),
    CONSTRAINT uk_mcp_server_team_name UNIQUE (team_id, name),
    CONSTRAINT ck_mcp_server_auth CHECK (auth_type IN ('NONE', 'API_KEY', 'BEARER_TOKEN', 'BASIC'))
);

CREATE INDEX idx_mcp_server_team_id ON mcp_server (team_id);

CREATE TABLE mcp_server_header
(
    mcp_server_id BIGINT        NOT NULL REFERENCES mcp_server (id) ON DELETE CASCADE,
    position      INT           NOT NULL,
    name          VARCHAR(255)  NOT NULL,
    value         VARCHAR(1000) NOT NULL,
    PRIMARY KEY (mcp_server_id, position)
);
