-- The execution module's tables: one row per run, the nodes as it ran them,
-- and the log it produced. Folded back in from orknux-workflow.
--
-- team_id and workflow_id are plain columns, for the same reason the connection
-- module's are: those tables belong to another module.

CREATE TABLE workflow_execution
(
    id            BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id       BIGINT                   NOT NULL,
    workflow_id   BIGINT                   NOT NULL,
    workflow_name VARCHAR(255)             NOT NULL,
    status        VARCHAR(16)              NOT NULL,
    trigger_type  VARCHAR(16)              NOT NULL,
    started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Null while the run is still going.
    finished_at   TIMESTAMP WITH TIME ZONE,
    -- What the run was handed by whatever asked for it.
    input         TEXT,
    error         VARCHAR(1000),
    CONSTRAINT ck_execution_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_execution_trigger CHECK (trigger_type IN ('WEBHOOK', 'MANUAL', 'SCHEDULE', 'API'))
);

CREATE INDEX idx_workflow_execution_team ON workflow_execution (team_id, started_at DESC);
CREATE INDEX idx_workflow_execution_workflow ON workflow_execution (workflow_id, started_at DESC);

-- The graph as the run saw it, one row per node. Copied when the run starts, so
-- the detail still shows what happened after the workflow is edited.
CREATE TABLE execution_step
(
    id           BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT           NOT NULL REFERENCES workflow_execution (id) ON DELETE CASCADE,
    node_key     VARCHAR(64)      NOT NULL,
    kind         VARCHAR(16)      NOT NULL,
    name         VARCHAR(255)     NOT NULL,
    description  VARCHAR(500),
    status       VARCHAR(16)      NOT NULL,
    position_x   DOUBLE PRECISION NOT NULL,
    position_y   DOUBLE PRECISION NOT NULL,
    -- The position in the run order, which is what the detail view reads by.
    step_order   INT              NOT NULL,
    started_at   TIMESTAMP WITH TIME ZONE,
    finished_at  TIMESTAMP WITH TIME ZONE,
    input        TEXT,
    output       TEXT,
    error        VARCHAR(1000),
    CONSTRAINT uk_execution_step UNIQUE (execution_id, node_key),
    CONSTRAINT ck_execution_step_kind CHECK (kind IN ('TRIGGER', 'AGENT', 'DATA_TASK', 'PUBLISH_TASK')),
    CONSTRAINT ck_execution_step_status
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED'))
);

CREATE INDEX idx_execution_step_execution ON execution_step (execution_id, step_order);

CREATE TABLE execution_log
(
    id           BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT                   NOT NULL REFERENCES workflow_execution (id) ON DELETE CASCADE,
    -- Null for lines about the run itself rather than one step.
    node_key     VARCHAR(64),
    logged_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    level        VARCHAR(16)              NOT NULL,
    message      VARCHAR(2000)            NOT NULL,
    -- Keeps lines logged in the same instant in the order they happened.
    sequence_no  INT                      NOT NULL,
    CONSTRAINT ck_execution_log_level CHECK (level IN ('INFO', 'SUCCESS', 'ERROR'))
);

CREATE INDEX idx_execution_log_execution ON execution_log (execution_id, sequence_no);
