-- Functions are named JavaScript a team writes; actions are the reusable blocks
-- a workflow is built from, and one kind of action calls a function.

CREATE TABLE workflow_function
(
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id          BIGINT       NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    -- A JavaScript identifier: what an action names when it calls this.
    name             VARCHAR(120) NOT NULL,
    description      VARCHAR(500),
    source           TEXT         NOT NULL,
    return_type      VARCHAR(16)  NOT NULL,
    last_modified_at TIMESTAMPTZ  NOT NULL,
    last_modified_by VARCHAR(120) NOT NULL,
    CONSTRAINT uk_workflow_function_name UNIQUE (team_id, name),
    CONSTRAINT ck_workflow_function_return
        CHECK (return_type IN ('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'ARRAY'))
);

CREATE TABLE workflow_function_param
(
    function_id BIGINT      NOT NULL REFERENCES workflow_function (id) ON DELETE CASCADE,
    position    INTEGER     NOT NULL,
    name        VARCHAR(64) NOT NULL,
    type        VARCHAR(16) NOT NULL,
    PRIMARY KEY (function_id, position),
    CONSTRAINT ck_workflow_function_param_type
        CHECK (type IN ('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'ARRAY'))
);

CREATE TABLE workflow_action
(
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id                BIGINT       NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    name                   VARCHAR(120) NOT NULL,
    -- What it does: run something, or wait for something.
    type                   VARCHAR(16)  NOT NULL,
    -- How it does it. The columns below are the settings of one subtype each.
    subtype                VARCHAR(24)  NOT NULL,
    -- Outgoing connection. The connection module owns that table, so no key.
    connection_id          BIGINT,
    connection_action      VARCHAR(32),
    content                TEXT,
    target                 VARCHAR(16),
    target_name            VARCHAR(120),
    -- HTTP request.
    url                    VARCHAR(1000),
    method                 VARCHAR(8),
    headers                TEXT,
    -- Function call.
    function_id            BIGINT REFERENCES workflow_function (id) ON DELETE SET NULL,
    -- Wait.
    condition_expression   VARCHAR(500),
    timeout_seconds        INTEGER,
    retry_interval_seconds INTEGER,
    duration_seconds       INTEGER,
    CONSTRAINT uk_workflow_action_name UNIQUE (team_id, name),
    CONSTRAINT ck_workflow_action_type CHECK (type IN ('EXECUTE', 'WAIT')),
    CONSTRAINT ck_workflow_action_subtype
        CHECK (subtype IN ('OUTGOING_CONNECTION', 'HTTP_REQUEST', 'FUNCTION', 'CONDITION', 'TIME')),
    -- A subtype belongs to one type, and each needs the setting it runs on.
    CONSTRAINT ck_workflow_action_shape CHECK (
        (type = 'EXECUTE' AND subtype = 'OUTGOING_CONNECTION' AND connection_id IS NOT NULL)
            OR (type = 'EXECUTE' AND subtype = 'HTTP_REQUEST' AND url IS NOT NULL)
            OR (type = 'EXECUTE' AND subtype = 'FUNCTION' AND function_id IS NOT NULL)
            OR (type = 'WAIT' AND subtype = 'CONDITION' AND condition_expression IS NOT NULL)
            OR (type = 'WAIT' AND subtype = 'TIME' AND duration_seconds IS NOT NULL)
        )
);

-- Which action input goes to which function argument, for a FUNCTION action.
CREATE TABLE workflow_action_mapping
(
    action_id  BIGINT       NOT NULL REFERENCES workflow_action (id) ON DELETE CASCADE,
    position   INTEGER      NOT NULL,
    argument   VARCHAR(64)  NOT NULL,
    expression VARCHAR(500) NOT NULL,
    PRIMARY KEY (action_id, position)
);

-- An action node is an instance of an action, the way a trigger node is an
-- instance of a trigger definition.
ALTER TABLE workflow_node
    ADD COLUMN action_id BIGINT REFERENCES workflow_action (id) ON DELETE SET NULL;

ALTER TABLE workflow_node
    DROP CONSTRAINT ck_workflow_node_kind;
ALTER TABLE workflow_node
    ADD CONSTRAINT ck_workflow_node_kind
        CHECK (kind IN ('TRIGGER', 'AGENT', 'ACTION', 'DATA_TASK', 'PUBLISH_TASK'));

-- The run keeps its own copy of which action a step was, so editing the action
-- afterwards does not rewrite what the run did.
ALTER TABLE execution_step
    ADD COLUMN action_id BIGINT;

ALTER TABLE execution_step
    DROP CONSTRAINT ck_execution_step_kind;
ALTER TABLE execution_step
    ADD CONSTRAINT ck_execution_step_kind
        CHECK (kind IN ('TRIGGER', 'AGENT', 'ACTION', 'DATA_TASK', 'PUBLISH_TASK'));

CREATE INDEX idx_workflow_node_action ON workflow_node (action_id) WHERE action_id IS NOT NULL;
CREATE INDEX idx_workflow_action_team ON workflow_action (team_id);
CREATE INDEX idx_workflow_function_team ON workflow_function (team_id);
