-- LLM providers, the models a team may reach through them, and what each model
-- has been used for.
--
-- A provider holds a credential, so it belongs to the connection module for the
-- same reason an MCP server does: credentials are read in one place. Models
-- hang off a provider, and a model's quotas are the team's own policy rather
-- than anything the provider enforces.

CREATE TABLE model_provider
(
    id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id  BIGINT        NOT NULL,
    name     VARCHAR(120)  NOT NULL,
    endpoint VARCHAR(1000) NOT NULL,
    -- Every LLM provider authenticates with a key, so there is no auth type to
    -- choose. A provider counts as connected once one is stored.
    secret   VARCHAR(1000),
    CONSTRAINT uk_model_provider_name UNIQUE (team_id, name)
);

CREATE INDEX idx_model_provider_team ON model_provider (team_id);

CREATE TABLE llm_model
(
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id             BIGINT        NOT NULL REFERENCES model_provider (id) ON DELETE CASCADE,
    -- What a person calls it, and what the provider's API is given.
    name                    VARCHAR(120)  NOT NULL,
    model_id                VARCHAR(200)  NOT NULL,
    kind                    VARCHAR(16)   NOT NULL DEFAULT 'CHAT',
    context_window          INT,
    max_output              INT,
    enabled                 BOOLEAN       NOT NULL DEFAULT TRUE,
    -- The team's own quotas. Null is no limit.
    token_limit             BIGINT,
    reset_interval          VARCHAR(16)   NOT NULL DEFAULT 'MONTHLY',
    requests_per_minute     INT,
    -- What the provider charges, so a cost can be worked out from tokens that
    -- were really used rather than guessed at.
    input_cost_per_million  NUMERIC(12, 4),
    output_cost_per_million NUMERIC(12, 4),
    CONSTRAINT uk_llm_model_name UNIQUE (provider_id, name),
    CONSTRAINT ck_llm_model_kind CHECK (kind IN ('CHAT', 'EMBEDDING', 'COMPLETION')),
    CONSTRAINT ck_llm_model_reset CHECK (reset_interval IN ('DAILY', 'WEEKLY', 'MONTHLY', 'NEVER'))
);

CREATE INDEX idx_llm_model_provider ON llm_model (provider_id);

-- One row per model per day, so the metrics are a sum over real calls rather
-- than a number kept somewhere and hoped to be right. Nothing writes here until
-- something actually calls a model.
CREATE TABLE model_usage_day
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id             BIGINT NOT NULL REFERENCES llm_model (id) ON DELETE CASCADE,
    day                  DATE   NOT NULL,
    requests             INT    NOT NULL DEFAULT 0,
    input_tokens         BIGINT NOT NULL DEFAULT 0,
    output_tokens        BIGINT NOT NULL DEFAULT 0,
    -- Summed, not averaged: an average of averages is not an average.
    latency_millis_total BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_model_usage_day UNIQUE (model_id, day)
);

CREATE INDEX idx_model_usage_day_model ON model_usage_day (model_id, day);

ALTER TABLE team_audit
    DROP CONSTRAINT ck_team_audit_category;

ALTER TABLE team_audit
    ADD CONSTRAINT ck_team_audit_category
        CHECK (category IN ('TEAM', 'WORKFLOW', 'AGENT', 'INTEGRATION', 'MODEL'));
