-- No foreign key to team: audit rows outlive the teams they describe (REMOVE).
CREATE TABLE team_audit
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id        BIGINT                   NOT NULL,
    old_team_name  VARCHAR(255),
    new_team_name  VARCHAR(255),
    operation_type VARCHAR(16)              NOT NULL,
    date           TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id        VARCHAR(255)             NOT NULL,
    CONSTRAINT ck_team_audit_operation_type CHECK (operation_type IN ('ADD', 'REMOVE', 'RENAME'))
);

CREATE INDEX idx_team_audit_team_id ON team_audit (team_id);
