-- What a workspace has decided and wants its agents to keep knowing.
--
-- A catalog is a folder, and a memory is one thing written down in it. The two
-- are separate tables rather than a tag on one, because the screen is a list of
-- catalogs beside the memories of the one selected: a catalog exists, and is
-- worth counting, before anything is in it.

CREATE TABLE memory_catalog (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT       NOT NULL,
    name         VARCHAR(120) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by   VARCHAR(120) NOT NULL,
    CONSTRAINT uk_memory_catalog_name UNIQUE (workspace_id, name)
);

CREATE INDEX idx_memory_catalog_workspace ON memory_catalog (workspace_id);

CREATE TABLE memory (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Deleting a catalog takes its memories: a memory outside one has nowhere
    -- to be shown, and the screen has no home for orphans.
    catalog_id       BIGINT       NOT NULL REFERENCES memory_catalog (id) ON DELETE CASCADE,
    title            VARCHAR(200) NOT NULL,
    content          TEXT         NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Who added it, which the card shows and the author filter groups by.
    created_by       VARCHAR(120) NOT NULL,
    last_modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_modified_by VARCHAR(120) NOT NULL
);

CREATE INDEX idx_memory_catalog ON memory (catalog_id);

-- The default sort is newest change first, over one catalog.
CREATE INDEX idx_memory_modified ON memory (catalog_id, last_modified_at DESC);

-- Which catalogs an agent may read.
--
-- A grant, not a copy: an agent is given some of what the workspace knows, and
-- by name for the same reason `agent_mcp_server` is — an agent is configured
-- against what the workspace calls things.
CREATE TABLE agent_memory_catalog (
    agent_id BIGINT       NOT NULL REFERENCES agent (id) ON DELETE CASCADE,
    position INTEGER      NOT NULL,
    name     VARCHAR(120) NOT NULL,
    PRIMARY KEY (agent_id, position)
);

-- The audit log is written by every category, and the column checks the list it
-- knows. A new category without this is a constraint violation on the first
-- entry, which is how the API answers INTERNAL_ERROR rather than saving.
ALTER TABLE workspace_audit DROP CONSTRAINT ck_workspace_audit_category;
ALTER TABLE workspace_audit ADD CONSTRAINT ck_workspace_audit_category
    CHECK (category IN ('WORKSPACE', 'WORKFLOW', 'AGENT', 'INTEGRATION', 'MODEL', 'MEMORY'));
