-- A workspace's data structures, named once and referred to from everywhere else.
--
-- What a trigger emits, what a function takes and returns, what an agent is
-- asked to produce: all of these are shapes, and until now each was described
-- only by the free text somebody typed into a mapping. A named object is what
-- lets a mapping be offered and checked rather than guessed at.
--
-- Fields only for now. The table is called `object` and its rows own `members`
-- rather than `fields`, so behaviour could be added later without the name
-- becoming a lie — which is exactly what calling it a Record would have cost.
CREATE TABLE workflow_object
(
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id      BIGINT       NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    name              VARCHAR(64)  NOT NULL,
    description       TEXT,
    created_at        TIMESTAMPTZ  NOT NULL,
    created_by        VARCHAR(255) NOT NULL,
    last_modified_at  TIMESTAMPTZ  NOT NULL,
    last_modified_by  VARCHAR(255) NOT NULL,
    CONSTRAINT uk_workflow_object_name UNIQUE (workspace_id, name)
);

-- One property of an object, in the order the editor shows them.
--
-- `kind` is the shape; `ref_object_id` names another object when the shape is
-- one (OBJECT, or ARRAY of one) and `element_kind` the scalar when it is an
-- array of those. A reference is a foreign key rather than a name, so renaming
-- an object cannot leave a property pointing at nothing.
CREATE TABLE object_property
(
    object_id     BIGINT      NOT NULL REFERENCES workflow_object (id) ON DELETE CASCADE,
    position      INTEGER     NOT NULL,
    name          VARCHAR(64) NOT NULL,
    kind          VARCHAR(16) NOT NULL,
    ref_object_id BIGINT      REFERENCES workflow_object (id),
    element_kind  VARCHAR(16),
    PRIMARY KEY (object_id, position)
);

CREATE INDEX idx_object_property_ref ON object_property (ref_object_id);

-- Objects are audited like everything else a workspace owns.
ALTER TABLE workspace_audit DROP CONSTRAINT ck_workspace_audit_category;
ALTER TABLE workspace_audit ADD CONSTRAINT ck_workspace_audit_category
    CHECK (category IN ('WORKSPACE', 'WORKFLOW', 'AGENT', 'INTEGRATION', 'MODEL', 'MEMORY', 'OBJECT'));
