-- Folders for skills, the way memory has them.
--
-- A workspace accumulates skills the same way it accumulates memories, and a
-- flat list stops being navigable at about the same size. The catalog is also
-- the unit an agent is granted: deciding per skill is a decision nobody wants to
-- make twice a week, and deciding per catalog is one somebody makes once.
CREATE TABLE skill_catalog
(
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT       NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    name         VARCHAR(120) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    created_by   VARCHAR(120) NOT NULL,
    CONSTRAINT uk_skill_catalog_name UNIQUE (workspace_id, name)
);

ALTER TABLE agent_skill ADD COLUMN catalog_id BIGINT REFERENCES skill_catalog (id);

-- Skills already exist, and a skill with nowhere to live would vanish from a
-- screen that lists catalogs. Every workspace holding any gets a General, and
-- what it holds moves there — which is also what the column can then be
-- declared NOT NULL on.
INSERT INTO skill_catalog (workspace_id, name, created_at, created_by)
SELECT DISTINCT workspace_id, 'General', now(), 'system'
FROM agent_skill;

UPDATE agent_skill s
SET catalog_id = c.id
FROM skill_catalog c
WHERE c.workspace_id = s.workspace_id
  AND c.name = 'General'
  AND s.catalog_id IS NULL;

ALTER TABLE agent_skill ALTER COLUMN catalog_id SET NOT NULL;

CREATE INDEX idx_skill_catalog ON agent_skill (catalog_id);

-- Which catalogs an agent may draw on. A grant, not a copy, and by name for the
-- same reason `agent_memory_catalog` is: an agent is configured against what the
-- workspace calls things.
CREATE TABLE agent_skill_catalog (
    agent_id BIGINT       NOT NULL REFERENCES agent (id) ON DELETE CASCADE,
    position INTEGER      NOT NULL,
    name     VARCHAR(120) NOT NULL,
    PRIMARY KEY (agent_id, position)
);
