-- Files attached to a chat, and the switches an administrator has thrown.
--
-- The row is the record; the bytes are wherever the configured storage put them.
-- Keeping the location as text rather than a path column is what lets object
-- storage arrive later as a class rather than as a migration of everything
-- anybody has uploaded.
--
-- The workspace is on the row rather than reached through the chat: it is what
-- decides who may read the file, and it is how the bytes are filed on disk —
-- one directory per workspace, so a mistake in a query cannot hand somebody
-- another workspace's document.
CREATE TABLE chat_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    -- Null while it is attached to a message nobody has sent yet.
    chat_session_id BIGINT REFERENCES chat_session (id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,
    location VARCHAR(1000) NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    uploaded_by VARCHAR(120) NOT NULL DEFAULT ''
);

CREATE INDEX idx_chat_attachment_workspace ON chat_attachment (workspace_id);
CREATE INDEX idx_chat_attachment_session ON chat_attachment (chat_session_id);

-- What an administrator has changed from the screen.
--
-- A key and a value, because these are few and unrelated: a table per switch
-- would be a migration every time somebody is given one. What is here overrides
-- the configuration file — except that a file which says no is final, since the
-- operator owns the disk and a browser does not.
CREATE TABLE installation_setting (
    name VARCHAR(120) PRIMARY KEY,
    value VARCHAR(500) NOT NULL,
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_by VARCHAR(120) NOT NULL DEFAULT ''
);
