CREATE TABLE agent
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id       BIGINT       NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    type          VARCHAR(16)  NOT NULL,
    description   VARCHAR(500),
    system_prompt TEXT,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_agent_team_name UNIQUE (team_id, name),
    CONSTRAINT ck_agent_type CHECK (type IN ('REACT', 'LLM'))
);

CREATE INDEX idx_agent_team_id ON agent (team_id);

-- The MCP servers an agent may connect to, kept in the order they were added.
CREATE TABLE agent_mcp_server
(
    agent_id BIGINT       NOT NULL REFERENCES agent (id) ON DELETE CASCADE,
    position INT          NOT NULL,
    name     VARCHAR(255) NOT NULL,
    PRIMARY KEY (agent_id, position)
);
