-- The people this installation knows, written down.
--
-- Until now a user was whatever the directory said at sign-in: a username on a
-- session, a name in the audit log, and nothing anywhere to list, assign, or
-- point an issue at. This is that list.
--
-- Two kinds. EXTERNAL is somebody the identity provider vouches for - recorded
-- when they sign in, named and given roles by the provider, and not editable
-- here because here is not where they are true. INTERNAL is somebody this
-- installation made up: an identity to assign and mention, managed entirely in
-- the app. Nothing about this table signs anybody in; the front door still
-- belongs to LDAP or OIDC.
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(120) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    type VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_by VARCHAR(120) NOT NULL DEFAULT 'system'
);

-- One person per name, whichever kind they are: an internal user shadowing an
-- external one would be two answers to "who is alice".
CREATE UNIQUE INDEX app_user_username_key ON app_user (lower(username));

-- The roles an internal user is assigned. An external user's roles arrive with
-- them at sign-in and are recorded on the row below at that moment; these
-- assignments are only ever written for internal users.
CREATE TABLE app_user_role (
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES security_role (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Everyone the audit log has ever seen act, so the list is not empty on the
-- day it appears. They signed in to do what the log records, so EXTERNAL.
INSERT INTO app_user (username, display_name, type)
SELECT DISTINCT user_id, user_id, 'EXTERNAL'
FROM workspace_audit
WHERE user_id IS NOT NULL AND user_id <> '';
