-- A workspace's own issue tracker.
--
-- Small on purpose: what a workspace needs is somewhere to write down what is
-- wrong with a workflow and who is looking at it, beside the workflow rather
-- than in another product. Title, state, description, labels, reporter,
-- assignee, comments - the shape everybody already knows from GitHub and Gitea,
-- and nothing past it.
--
-- Numbered per workspace, not globally: "#3" means the third issue in this
-- workspace, the way it does everywhere else, and an id nobody sees stays the
-- key. The number is allocated under the workspace's own row, so two people
-- filing at once cannot be given the same one.
CREATE TABLE workspace_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    number INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',

    /*
     * Who filed it: a username, as the audit log records one. A name rather
     * than a foreign key, because the person who filed an issue stays the
     * person who filed it even if their row is removed later - and an issue
     * that lost its reporter would be an issue nobody can ask about.
     */
    reporter VARCHAR(120) NOT NULL,

    /*
     * Who is looking at it, which may not be a person.
     *
     * An agent or a model can be the assignee - this is a product where the
     * thing doing the work is often not human - so the assignee is a kind and
     * an id, resolved to a name when it is read. Null for nobody.
     */
    assignee_kind VARCHAR(16),
    assignee_id VARCHAR(120),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_by VARCHAR(120) NOT NULL DEFAULT 'system'
);

CREATE UNIQUE INDEX workspace_issue_number_key ON workspace_issue (workspace_id, number);
CREATE INDEX workspace_issue_status_idx ON workspace_issue (workspace_id, status);

-- Free text, one row each, so filtering by label is a join rather than a LIKE
-- over a comma-separated column.
CREATE TABLE workspace_issue_label (
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,
    label VARCHAR(60) NOT NULL,
    PRIMARY KEY (issue_id, label)
);

CREATE TABLE workspace_issue_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,
    author VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX workspace_issue_comment_issue_idx ON workspace_issue_comment (issue_id, created_at);
