-- Credentials for the people this installation made up.
--
-- An internal user was an identity and nothing else: somewhere to point an
-- issue, a name to show. That is still what most of them are - the column is
-- nullable, and a user without one simply cannot sign in - but an identity that
-- can never act is a poor place to assign work to, and an assistant working
-- through the API needs to be somebody rather than borrowing an administrator's
-- session.
--
-- Only ever a hash, and only for INTERNAL users: an external user's password
-- belongs to the directory that keeps it, and writing one here would be this
-- installation quietly becoming a second place to change it.
ALTER TABLE app_user
    ADD COLUMN password_hash VARCHAR(100);

-- Tokens, for the callers that are not sitting at a browser.
--
-- A token is the same person by a different door: it carries a user and takes
-- their roles, so what it may do is what they may do, and nothing about it is a
-- second permission system.
--
-- Stored hashed, like the password. The secret is shown once when it is made
-- and never again - a token this table could give back would be a password
-- written down in a database, which is exactly what the column above is not.
CREATE TABLE app_user_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,

    /* What it is for, in the words of whoever made it: "Claude Code", "CI". */
    name VARCHAR(120) NOT NULL,

    /* SHA-256 of the secret. A token is long and random, so a slow hash buys
       nothing here that its own entropy has not already bought. */
    token_hash VARCHAR(64) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    /* When it was last accepted, so a token nobody uses can be found and
       removed rather than living forever out of caution. */
    last_used_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX app_user_token_hash_key ON app_user_token (token_hash);
CREATE INDEX app_user_token_user_idx ON app_user_token (user_id);
