-- What happened on an issue, addressed to whoever should hear about it.
--
-- The tracker already records everything in the issue itself, and that is no
-- use to somebody who is not looking at it: an assistant working through a
-- queue has no way to learn that a comment arrived except by being told, which
-- is exactly the telling this removes.
--
-- One row per event per audience, rather than one row per event. It costs a
-- duplicate when an issue's assignee is also its reporter - which is excluded
-- anyway, since nobody needs telling what they just did - and it buys a read
-- that is a single indexed scan for "what concerns me", with no join to an
-- issue whose assignee may since have changed. Who an event was for is a fact
-- about the moment it happened, not a fact about the issue now.
CREATE TABLE issue_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,

    /*
     * The number people say, copied rather than looked up. An event survives
     * its issue being deleted only as long as this row does - but while it is
     * here it must read as "#4" without a second query.
     */
    issue_number INT NOT NULL,
    issue_title VARCHAR(200) NOT NULL,

    /* ASSIGNED, STATUS or COMMENT. */
    kind VARCHAR(16) NOT NULL,
    actor VARCHAR(120) NOT NULL,

    /* The new status, or the first of what was said. Null for an assignment. */
    says TEXT,

    /*
     * Who should hear it: the same kind and id an assignee is, because an
     * audience is an assignee - a person, an agent, or a model.
     *
     * The name is kept beside the id because the id alone cannot be matched
     * against the caller when the caller is a person: a token knows the
     * username it was minted for, an issue knows the user row it points at,
     * and one of the two has to be resolvable from the other without a join
     * per event.
     */
    audience_kind VARCHAR(16) NOT NULL,
    audience_id VARCHAR(120),
    audience_name VARCHAR(120) NOT NULL,

    at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX issue_news_audience_idx ON issue_news (workspace_id, audience_kind, audience_name, id);

-- How far through the news somebody has read.
--
-- Kept here rather than handed back for the client to remember: a client that
-- forgets its cursor either repeats a week of events or silently skips them,
-- and an assistant restarted between sessions forgets everything. The reader
-- is named the way the news is addressed.
CREATE TABLE issue_news_read (
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    reader_kind VARCHAR(16) NOT NULL,
    reader_name VARCHAR(120) NOT NULL,
    last_id BIGINT NOT NULL,
    at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, reader_kind, reader_name)
);
