-- Runs of a workflow for one team. Nothing executes workflows yet; this is the
-- store an execution engine would write to and the executions view reads from.
CREATE TABLE workflow_execution
(
    id           BIGINT                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id      BIGINT                   NOT NULL REFERENCES team (id) ON DELETE CASCADE,
    workflow_id  BIGINT                   NOT NULL REFERENCES workflow (id) ON DELETE CASCADE,
    status       VARCHAR(16)              NOT NULL,
    trigger_type VARCHAR(16)              NOT NULL,
    started_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Null while the run is still going.
    finished_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_execution_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_execution_trigger CHECK (trigger_type IN ('WEBHOOK', 'MANUAL', 'SCHEDULE', 'API'))
);

CREATE INDEX idx_workflow_execution_team ON workflow_execution (team_id, started_at DESC);
