-- What a plugin has to be told, and what each workspace tells it.
--
-- Until now a plugin could only work with what a node passed into one of its
-- functions, which is no use to a plugin that has to talk to something: an
-- address, a project key and a token are not things a graph should be carrying
-- around. A plugin now declares what it needs, and a workspace answers.
--
-- Two halves, in two places, because they belong to two people. The declaration
-- is the plugin's and arrives with it, so it sits on the plugin row and is
-- replaced wholesale every time the plugin is loaded. The answers are the
-- workspace's - the same plugin points at two different projects for two
-- different teams - so they are rows of their own, keyed by workspace.

-- The declaration, as JSON, the same way declared_functions is kept. Each entry
-- is a name, a type, whether the plugin can work without it, and whether the
-- plugin says it is asking for a secret.
ALTER TABLE plugin ADD COLUMN declared_parameters TEXT NOT NULL DEFAULT '[]';

CREATE TABLE plugin_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Gone with the plugin. An answer to a question nobody is asking any more is
    -- not worth keeping, and a plugin loaded again keeps its id, so replacing a
    -- plugin does not lose what workspaces set it to.
    plugin_id BIGINT NOT NULL REFERENCES plugin (id) ON DELETE CASCADE,

    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,

    -- The name the plugin declared. Not a foreign key, because the declaration
    -- is JSON on the plugin row; a row naming a parameter the plugin no longer
    -- declares is simply never read.
    name VARCHAR(64) NOT NULL,

    -- Exactly one of these two is set, which the check below insists on.
    --
    -- A literal is stored as it was typed, in the clear, because the screen shows
    -- it back so it can be edited. That is why a parameter the plugin declared as
    -- a secret cannot be a literal at all: the only way to answer one of those is
    -- to point at a variable, and a variable is encrypted at rest.
    literal_value TEXT,

    -- One of the workspace's variables, read when the plugin runs rather than
    -- copied here. Rotating a token then means changing it in one place, and this
    -- table never holds a secret of its own.
    --
    -- Nulled rather than cascaded when the variable goes: the parameter is then
    -- reported as missing, which is the truth about what will happen if the
    -- plugin runs, where a row that vanished would look like nobody ever set it.
    variable_id BIGINT REFERENCES workspace_variable (id) ON DELETE SET NULL,

    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_by VARCHAR(120) NOT NULL DEFAULT '',

    CONSTRAINT plugin_parameter_one_source CHECK (
        (literal_value IS NOT NULL AND variable_id IS NULL)
        OR (literal_value IS NULL AND variable_id IS NOT NULL)
        -- Both null is what a reference whose variable was deleted becomes, and
        -- it has to be storable or the delete above would fail instead.
        OR (literal_value IS NULL AND variable_id IS NULL)
    )
);

-- One answer per parameter per workspace. Setting one twice is an edit, not a
-- second row, and the unique index is what makes that true rather than the code.
CREATE UNIQUE INDEX plugin_parameter_unique_idx ON plugin_parameter (plugin_id, workspace_id, name);

-- Every answer for one workspace's copy of one plugin, which is what both the
-- page and the run ask for.
CREATE INDEX plugin_parameter_workspace_idx ON plugin_parameter (workspace_id, plugin_id);
