-- Who else wants to hear about an issue.
--
-- Until now an issue's news reached exactly two people: whoever has it and
-- whoever filed it. That is the right pair for work somebody has been handed,
-- and it is nobody at all for work that has not - an assistant filing what it
-- found, assigned to no one because handing out work is not its judgement,
-- produced a tracker full of issues whose every comment was addressed to an
-- empty list. Observers are how somebody says "tell me about this one" without
-- anybody having to be given it.
--
-- Its own table rather than a column on the issue, because it is a list and a
-- list in a column is a list nobody can index, count or take one row off. Rows
-- of its own also carry who put somebody here, which is what makes the audit
-- line readable afterwards.
CREATE TABLE workspace_issue_observer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Not null: an observer is chosen on an issue that already exists, so
    -- there is no moment where the row is here and the issue is not.
    issue_id BIGINT NOT NULL REFERENCES workspace_issue (id) ON DELETE CASCADE,

    /*
     * The same kind and id an assignee is, and deliberately not the same set of
     * kinds. A person or an agent can be an observer; a model cannot, because
     * observing is a statement about who reads and nothing anywhere reads a
     * model's news - a model is a thing work is given to, not a thing that asks
     * what happened.
     *
     * An id rather than a name, unlike the reporter beside it. A reporter is a
     * record of something that happened and stays true after the row it names
     * is gone; an observer is a live subscription, and one pointing at somebody
     * who is no longer here is a subscription to nothing.
     */
    observer_kind VARCHAR(16) NOT NULL,
    observer_id VARCHAR(120) NOT NULL,

    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Who put them here: themselves, in the ordinary case, or an administrator
    -- who decided somebody should be hearing about this.
    added_by VARCHAR(120) NOT NULL DEFAULT ''
);

-- Twice on the same issue is the same subscription, so the table refuses it
-- rather than leaving two rows to be deduplicated on every read.
CREATE UNIQUE INDEX workspace_issue_observer_key
    ON workspace_issue_observer (issue_id, observer_kind, observer_id);
