-- Which outbound addresses have to go through a proxy, and which one.
--
-- Until now every call this installation makes went out the way the host does,
-- which is right until one endpoint is not reachable that way. The case that
-- prompted this is real and narrow: everything works direct except the Entra ID
-- token endpoint, which the network insists is reached through a proxy. Setting
-- a proxy for the whole process would send every other call through it too,
-- which is a much larger change than the problem asked for.
--
-- So the unit is a rule: a regular expression matched against the request URL,
-- the proxy that URL goes through, optional credentials for it, and a switch.
--
-- Installation-wide, with no workspace column. The reason a proxy exists is the
-- network this process sits in, not the team whose workflow made the call, and a
-- per-workspace copy would mean an endpoint that must be proxied works for
-- whoever remembered and fails for everybody else. It is also the only scope
-- that can cover the calls made for nobody in particular - the token grant a
-- provider needs, the sweep that asks whether connections still answer.

CREATE TABLE proxy_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What it is for, in the words of whoever wrote it: "Entra ID", "everything
    -- else". Unique so the page can name one rule without ambiguity and so the
    -- audit entry saying a rule was changed means a particular rule.
    name VARCHAR(120) NOT NULL,

    -- Matched against the whole request URL, found anywhere in it rather than
    -- end to end, ignoring case. Wide because a pattern listing several hosts
    -- gets long, and it is not a URL - it is an expression about URLs.
    pattern VARCHAR(1000) NOT NULL,

    -- Host and port rather than a proxy URL. The JDK's HTTP client speaks to a
    -- proxy over plain HTTP and tunnels everything else with CONNECT, so an
    -- https:// in front of a proxy address would be accepted on the screen and
    -- quietly ignored on the wire. Two columns cannot say something untrue.
    proxy_host VARCHAR(255) NOT NULL,
    proxy_port INTEGER NOT NULL,

    -- Optional: plenty of proxies want nobody in particular.
    username VARCHAR(255),

    -- Encrypted, the same way every other credential on this platform is, by the
    -- converter on the entity rather than by anything at a call site. Wide
    -- enough for the envelope, which is base64 around the bytes plus an
    -- initialisation vector, a tag and a version prefix.
    password VARCHAR(4000),

    -- Off is not deleted. A rule somebody is testing, or one kept for the next
    -- time the network does this, should be able to sit there doing nothing.
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    -- Which rule answers when more than one could: ascending, first match wins.
    --
    -- A number an administrator sets rather than something worked out from the
    -- patterns. Deciding which of two regular expressions is the more specific
    -- is not something that can be done soundly, and a rule losing to another
    -- because of a guess would be exactly the silent failure the page exists to
    -- prevent. Stated instead, shown on the page, and answerable for any URL.
    position INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX proxy_rule_name_key ON proxy_rule (name);

-- The order they are consulted in, which is the only way they are ever read.
CREATE INDEX proxy_rule_position_idx ON proxy_rule (position, id);
