-- The bridge between this application and an operating system, over SSH.
--
-- Until now nothing here could run a command anywhere. A workflow could call an
-- HTTP endpoint, send mail or run a script inside this process, and an agent
-- could ask orknux about orknux - but the ordinary thing somebody wants of an
-- assistant sitting next to their infrastructure, "look at that box and tell me
-- what is wrong with it", had no answer at all.
--
-- A shell is a named SSH target: a host, a port, a user and a private key. The
-- containment boundary is that target and nothing else. This deliberately holds
-- no denylist of commands and no classifier deciding which are safe, because
-- deciding what a shell command does by looking at it is not a solvable problem
-- and a list that is nearly right is worse than no list - it tells an
-- administrator they are protected when they are not. The design instead is
-- that the target is a virtual machine or a container the administrator chose
-- and is willing to lose, and everything that runs through here is written down
-- in the audit log so they can see what happened on it.
--
-- Installation-wide, with no workspace column, for the same reason a proxy rule
-- is: a machine belongs to the infrastructure this process sits in rather than
-- to the team whose agent asked about it, and an administrator is the only
-- person who should be deciding which hosts this application can reach.

CREATE TABLE shell (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What the box is called in the words of whoever added it: "build box",
    -- "staging". Unique so that an audit entry saying a command ran on one
    -- means a particular machine.
    name VARCHAR(120) NOT NULL,

    host VARCHAR(255) NOT NULL,
    port INTEGER NOT NULL DEFAULT 22,

    -- The account on the other end. Which account it is is the whole of the
    -- privilege question, and it is the administrator's to answer.
    username VARCHAR(255) NOT NULL,

    -- Encrypted, the same way every other credential on this platform is, by the
    -- converter on the entity rather than by anything at a call site.
    --
    -- TEXT rather than the 4000 characters the other credentials get. A private
    -- key is already a few kilobytes before it is encrypted, and the envelope is
    -- base64 around the bytes plus an initialisation vector and a tag, so an
    -- RSA-4096 key in OpenSSH format lands past that limit. A column that is
    -- nearly wide enough fails on the largest key somebody owns, which is the
    -- worst moment to find out.
    private_key TEXT,

    -- Optional, and only meaningful with a key. Encrypted for the same reason
    -- the key is: a passphrase stored beside the thing it unlocks is not a
    -- second factor, but a passphrase readable in a database dump is a first
    -- one given away.
    key_passphrase VARCHAR(4000),

    -- Off is not deleted. A machine being rebuilt should be able to sit there
    -- doing nothing without anybody having to remember its key afterwards.
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    -- The host key this shell was first seen with, as a SHA-256 fingerprint.
    --
    -- Trust on first use, which is what an administrator does by hand the first
    -- time they type yes at ssh. The first successful connection records what
    -- answered; every one afterwards checks it and refuses if it changed. It is
    -- the cheapest defence against a machine standing in for the one whose key
    -- we are about to hand over, and "it is up to the admin to secure it" is
    -- only fair if the application is not quietly connecting to whatever answers
    -- on that address today.
    --
    -- Null until the first connection succeeds, and cleared by an administrator
    -- when a host is legitimately rebuilt.
    host_key VARCHAR(500),

    -- What the last probe found: NOT_CONFIGURED, NOT_CHECKED, CONNECTED, FAILED.
    -- The same four words the connections use, because they answer the same
    -- question and a second vocabulary for it would only be a second thing to
    -- learn.
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_CHECKED',
    last_check_message VARCHAR(500),
    last_checked_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_modified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX shell_name_key ON shell (name);

-- How a shell is chosen when an agent asks for one: enabled first, then the
-- ones known to answer, then by name. See ShellService for why that is the rule.
CREATE INDEX shell_choice_idx ON shell (enabled, status, name);


-- One agent's session on one shell, and the directory that belongs to it.
--
-- A row rather than a live connection held in this process's memory, which is
-- the decision the rest of this feature hangs off. A held connection dies with
-- the JVM, and when it dies the directory it made on the far side survives it
-- with nothing left anywhere that knows the directory was ever ours. A row
-- outlives a restart, so the sweep can still find the directory and remove it,
-- and every command simply opens a connection, runs, and closes.
--
-- What that costs is a connect per command, which is a fraction of a second and
-- buys a session that is not damaged by a deploy. What it also buys is that
-- nothing here holds an SSH channel open for as long as an agent is thinking.
CREATE TABLE shell_session (
    -- The id the agent is given and hands back, so it is opaque and unguessable
    -- rather than a number somebody could walk. It is also the directory's name
    -- on the far side, which is what makes an orphan identifiable by sight.
    id VARCHAR(64) PRIMARY KEY,

    shell_id BIGINT NOT NULL REFERENCES shell (id) ON DELETE CASCADE,

    -- Who opened it. An agent rather than a person: nobody is at a screen when a
    -- workflow runs one. Kept even after the agent is deleted, because the audit
    -- entry it belongs to outlives the agent.
    agent_id BIGINT,
    agent_name VARCHAR(120) NOT NULL,
    workspace_id BIGINT,

    -- The absolute path on the far side. Stored rather than derived so that a
    -- change to how paths are chosen cannot orphan the directories already out
    -- there under the old scheme.
    directory VARCHAR(500) NOT NULL,

    -- What the far side said it was, as reported to the agent.
    operating_system VARCHAR(200),

    -- OPEN, CLOSED, or EXPIRED - swept because nobody closed it.
    state VARCHAR(16) NOT NULL DEFAULT 'OPEN',

    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Touched by every command, because idleness is what the sweep measures. An
    -- agent working for an hour should keep its directory; one that opened a
    -- session and wandered off should not keep it forever.
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    closed_at TIMESTAMPTZ,

    -- How many commands ran in it, which is the cheap version of the question
    -- "was this session used at all".
    command_count INTEGER NOT NULL DEFAULT 0
);

-- The sweep's own query: the open ones, oldest use first.
CREATE INDEX shell_session_open_idx ON shell_session (state, last_used_at);

-- How many a given agent has open, which is the only cap here.
CREATE INDEX shell_session_agent_idx ON shell_session (agent_id, state);


-- Whether an agent may reach the shells at all.
--
-- Plural and unnamed on purpose. An agent is not configured against a
-- particular machine, because from where it sits the question is "can I run a
-- command somewhere" and not "may I run one on build-box-3" - naming one would
-- make every agent's configuration stale the day a machine is replaced.
ALTER TABLE agent ADD COLUMN shell_access BOOLEAN NOT NULL DEFAULT FALSE;


-- Commands run on a machine get an audit category of their own.
--
-- The constraint is a list rather than an enum type, so a new category has to be
-- added here as well as in the code; without this the first command an agent
-- runs fails on the audit entry rather than on anything to do with the machine,
-- which is a confusing way to find out.
--
-- Its own category rather than folded into AGENT or INTEGRATION, because this is
-- the one thing on the platform that acts outside it. "It is up to the
-- administrator to secure the box" is only a fair bargain if the administrator
-- can go to one place and read every command that was run on it.
ALTER TABLE workspace_audit DROP CONSTRAINT ck_workspace_audit_category;
ALTER TABLE workspace_audit ADD CONSTRAINT ck_workspace_audit_category
    CHECK (category IN ('WORKSPACE', 'WORKFLOW', 'AGENT', 'INTEGRATION', 'MODEL', 'MEMORY', 'OBJECT', 'CHAT', 'SHELL'));
