package io.mszymanski.orknux.server.plugin

import graphql.GraphQLError
import graphql.schema.DataFetchingEnvironment
import io.mszymanski.orknux.server.security.WorkspaceAccess
import io.mszymanski.orknux.server.workspace.WorkspaceAuditCategory
import io.mszymanski.orknux.server.workspace.WorkspaceAuditRecorder
import io.mszymanski.orknux.server.workspace.WorkspaceRepository
import io.mszymanski.orknux.workflow.script.PluginInspection
import io.mszymanski.orknux.workflow.script.PluginPermission
import io.mszymanski.orknux.workflow.script.PluginRunner
import org.springframework.http.HttpHeaders
import org.springframework.http.MediaType
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.data.repository.findByIdOrNull
import org.springframework.graphql.data.method.annotation.Argument
import org.springframework.graphql.data.method.annotation.MutationMapping
import org.springframework.graphql.data.method.annotation.QueryMapping
import org.springframework.graphql.execution.DataFetcherExceptionResolverAdapter
import org.springframework.graphql.execution.ErrorType
import org.springframework.http.ResponseEntity
import org.springframework.security.core.context.SecurityContextHolder
import org.springframework.stereotype.Component
import org.springframework.stereotype.Controller
import org.springframework.transaction.annotation.Transactional
import org.springframework.web.bind.annotation.ExceptionHandler
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.multipart.MultipartFile
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.time.OffsetDateTime

/**
 * Loading a plugin into the installation, and taking it out again.
 *
 * Administrators only, all of it: a plugin is installation-wide, so this is not a
 * workspace's decision to make.
 *
 * The upload is REST for the same reason attachments are — what crosses is a
 * file, and a multipart form is what a browser produces from a file picker.
 * Listing and unloading are GraphQL like everything else.
 *
 * The plugin is loaded and questioned as it arrives - what it calls itself, what
 * it offers, what it has to be told - and refused if it cannot answer. What each
 * workspace answers its parameters with is not decided here: see
 * [WorkspacePluginAPI], further down, for whose decision that is.
 */
@RestController
class PluginUploadAPI(
    private val plugins: PluginRepository,
    private val access: WorkspaceAccess,
    private val runner: PluginRunner,
    private val declarations: PluginDeclarations,
    private val registry: PluginFunctionRegistry,
    private val permissions: PluginPermissions,
) {

    /**
     * A plugin to start from.
     *
     * Generated by the server rather than kept in the browser, so it cannot
     * disagree with what this server actually accepts: the API version in it is
     * the one this build supports, and the example function declares itself the
     * way the loader expects to read it.
     */
    @GetMapping("/api/plugins/template")
    fun template(): ResponseEntity<String> {
        access.requireAdmin()
        return ResponseEntity.ok()
            /*
             * TypeScript, and the interface compiles it on the way back in.
             *
             * The sandbox runs JavaScript and this server has no compiler, so what is
             * stored and run is always JavaScript — but nobody writes a plugin against
             * an undocumented contract by choice. The declarations at the top of the
             * template are the contract, they are checked by any editor, and they
             * compile to nothing.
             */
            .contentType(MediaType.valueOf("text/plain"))
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"orknux-plugin.ts\"")
            .body(
                /*
                 * Filled in from what this server actually enforces — the version it
                 * runs, the versions it still accepts, and the value types it has — so a
                 * template can never describe a contract different from the one that
                 * will judge it.
                 */
                TEMPLATE.trimIndent()
                    .replace("@API_VERSION@", PluginApiVersions.CURRENT.toString())
                    .replace("@SUPPORTED@", PluginApiVersions.SUPPORTED.sorted().joinToString(", "))
                    /*
                     * The same list again, as a TypeScript union, so an editor refuses
                     * a type this server does not have rather than leaving it to be
                     * discovered on upload. Derived from the enum like everything else
                     * here: a template cannot describe a contract that is not the one
                     * doing the judging.
                     */
                    .replace(
                        "@VALUE_TYPE_UNION@",
                        declarations.usableTypes().joinToString(" | ") { "'$it'" },
                    )
                    /*
                     * Narrower than the union above, and deliberately so: a
                     * parameter is answered either by typing a value or by pointing
                     * at one of a workspace's variables, and a variable holds a
                     * scalar. The template offers exactly what the loader accepts.
                     */
                    .replace(
                        "@PARAMETER_TYPE_UNION@",
                        declarations.parameterTypes().joinToString(" | ") { "'$it'" },
                    )
                    /*
                     * The permissions this build can grant, as a union, so an
                     * editor refuses one this server has never heard of rather
                     * than leaving it to be discovered on upload. Written from the
                     * enumeration that does the granting: a template cannot
                     * describe a contract different from the one doing the judging.
                     */
                    .replace(
                        "@PERMISSION_UNION@",
                        PluginPermission.entries.joinToString(" | ") { "'${it.name}'" },
                    )
                    .replace(
                        "@PERMISSION_LIST@",
                        PluginPermission.entries.joinToString("\n") {
                            "   *   - `${it.name}` - ${it.summary.lowercase()}"
                        },
                    ),
            )
    }

    /**
     * Loads one plugin.
     *
     * A name already loaded is replaced rather than refused: iterating on a
     * plugin means uploading it again, and making somebody unload first to do
     * that is a step with nothing behind it. The row keeps its id, so anything
     * that comes to refer to a plugin refers to the same one across an update.
     */
    /**
     * The plugin as it was written, for downloading.
     *
     * TypeScript where there is any, JavaScript otherwise — that is what "the plugin"
     * means to whoever wrote it. Handing back the compiled output instead would hand
     * them something they did not write, with the annotations gone and no way back.
     */
    @GetMapping("/api/plugins/{id}/source")
    fun download(@PathVariable id: Long): ResponseEntity<String> {
        access.requireAdmin()
        val plugin = plugins.findByIdOrNull(id) ?: throw PluginNotFoundException(id)

        val typescript = plugin.typescript
        val extension = if (typescript == null) "js" else "ts"
        return ResponseEntity.ok()
            .contentType(MediaType.valueOf("text/plain"))
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"${plugin.key}.$extension\"")
            .body(typescript ?: plugin.source)
    }

    @PostMapping("/api/plugins")
    @Transactional
    fun upload(
        @RequestParam("file") file: MultipartFile,
        /*
         * What it was written in, when that was TypeScript.
         *
         * Sent by the interface, which compiles before uploading: the sandbox runs
         * JavaScript and this server has no compiler, so `file` is always the
         * compiled code. This is kept only so the plugin can be downloaded as the
         * thing somebody actually wrote — and it is never evaluated.
         */
        @RequestParam("typescript", required = false) typescript: String?,
        /*
         * Which permissions the person loading it is agreeing to, by name.
         *
         * A list rather than a flag, and that is the point of it. "Yes" would be
         * an agreement to whatever the file happened to ask for, including
         * whatever it started asking for since it was last looked at; naming them
         * is an agreement to these. A load whose names do not match exactly what
         * the plugin declares is refused, so this cannot drift from what was shown.
         */
        @RequestParam("accept", required = false) accept: String?,
    ): ResponseEntity<Any> {
        access.requireAdmin()

        if (file.isEmpty) throw PluginEmptyException()
        if (file.size > MAX_SIZE) throw PluginTooLargeException(MAX_SIZE / 1024)

        val filename = file.originalFilename?.trim()?.ifEmpty { null } ?: "plugin.js"
        if (!filename.endsWith(".js") && !filename.endsWith(".mjs")) throw PluginNotJavaScriptException(filename)

        val source = text(file.bytes)

        /*
         * The plugin is loaded and questioned before anything is stored: what it
         * calls itself, which API it was written against, and what it offers. One
         * evaluation, because all three answers have to come from the same instance
         * — and a plugin that fails the contract is not stored at all, so every row
         * here is a plugin that held it up.
         */
        val inspected = when (val answered = runner.inspect(source)) {
            is PluginInspection.Read -> answered
            is PluginInspection.Unreadable -> throw PluginContractException(answered.reason)
        }

        if (inspected.apiVersion !in PluginApiVersions.SUPPORTED) {
            throw PluginApiVersionUnsupportedException(inspected.apiVersion, PluginApiVersions.SUPPORTED)
        }

        val key = inspected.id
        if (!KEY.matches(key)) throw PluginIdInvalidException(key)

        val apiVersion = inspected.apiVersion
        val declared = declarations.validated(inspected.functions)
        val parameters = declarations.validatedParameters(inspected.parameters)

        /*
         * What it needs, and whether anybody has said it may have it.
         *
         * Three ways this goes, and only one of them grants anything new. Asking
         * for nothing needs no acceptance. Asking for what is already accepted
         * needs none either — nothing new is being handed over, and making somebody
         * agree again to what they agreed to last week teaches them to click
         * through it. Asking for anything else is refused, with the list, until a
         * second load names exactly that list.
         *
         * This is where an escalation is caught: a plugin edited to need one more
         * thing lands in the third case, because the acceptance on the row names
         * the permissions it was given for and not the plugin in general.
         */
        val wanted = permissions.validated(inspected.permissions)
        val already = plugins.findByKey(key)?.let { permissions.read(it.acceptedPermissions) } ?: emptySet()
        val agreeing = wanted.isNotEmpty() && !already.containsAll(wanted)
        if (agreeing && permissions.accepted(accept) != wanted) {
            throw PluginPermissionsNotAcceptedException(permissions.viewOf(wanted))
        }

        val name = filename.removeSuffix(".mjs").removeSuffix(".js").takeLast(MAX_NAME)

        val existing = plugins.findByKey(key)
        // Stamped when somebody has just agreed; carried over when nothing new was
        // granted; cleared with the list when the plugin stops asking for anything.
        val acceptedAt = when {
            wanted.isEmpty() -> null
            agreeing -> OffsetDateTime.now()
            else -> existing?.permissionsAcceptedAt ?: OffsetDateTime.now()
        }
        val acceptedBy = when {
            wanted.isEmpty() -> null
            agreeing -> currentUser()
            else -> existing?.permissionsAcceptedBy ?: currentUser()
        }

        val plugin = existing?.apply {
            this.name = name
            this.filename = filename.takeLast(MAX_NAME)
            this.source = source
            this.typescript = typescript?.ifBlank { null }
            this.sizeBytes = file.size
            this.apiVersion = apiVersion
            this.declaredFunctions = declared
            this.declaredParameters = parameters
            this.declaredPermissions = permissions.write(wanted)
            this.acceptedPermissions = permissions.write(wanted)
            this.permissionsAcceptedAt = acceptedAt
            this.permissionsAcceptedBy = acceptedBy
            this.sha256 = digest(source)
            this.uploadedAt = OffsetDateTime.now()
            this.uploadedBy = currentUser()
        } ?: Plugin(
            key = key,
            name = name,
            filename = filename.takeLast(MAX_NAME),
            source = source,
            typescript = typescript?.ifBlank { null },
            sizeBytes = file.size,
            apiVersion = apiVersion,
            declaredFunctions = declared,
            declaredParameters = parameters,
            declaredPermissions = permissions.write(wanted),
            /*
             * Accepted is set to exactly what is declared, never to more. The check
             * above is what decides whether that was allowed; by here it has been
             * agreed to, or there was nothing to agree to.
             */
            acceptedPermissions = permissions.write(wanted),
            permissionsAcceptedAt = acceptedAt,
            permissionsAcceptedBy = acceptedBy,
            sha256 = digest(source),
            uploadedBy = currentUser(),
        )

        val saved = plugins.save(plugin)
        // What it declares becomes what it provides, in the same transaction: a
        // plugin that is loaded but whose functions did not appear is a state
        // nobody could explain.
        val provided = registry.reconcile(saved)

        return ResponseEntity.ok(
            mapOf(
                "plugin" to saved.view(
                    declarations.read(saved.declaredFunctions),
                    declarations.readParameters(saved.declaredParameters),
                    permissions.viewOf(permissions.grantedTo(saved)),
                ),
                "replaced" to (existing != null),
                "provides" to provided,
            ),
        )
    }

    /**
     * A refused upload, answered as a refusal.
     *
     * Everything this endpoint rejects is something about the file somebody
     * chose — too large, not JavaScript, would not say which API it uses — so it
     * is a 400 carrying the sentence, not a 500. Scoped to this controller
     * because these exceptions mean nothing anywhere else.
     */
    /**
     * A plugin needing permissions nobody has agreed to, answered as the question
     * it is.
     *
     * Its own handler because the list has to travel: a message alone would leave
     * the interface with nothing to show, and something to accept that nobody was
     * shown is exactly what this is meant to prevent. The status is a 400 like
     * every other refusal — nothing was stored, and the way forward is a second
     * request.
     */
    @ExceptionHandler(PluginPermissionsNotAcceptedException::class)
    fun needsAccepting(failure: PluginPermissionsNotAcceptedException): ResponseEntity<Map<String, Any>> =
        ResponseEntity.badRequest().body(
            mapOf(
                "message" to (failure.message ?: "This plugin needs permissions"),
                "permissions" to failure.needed.map { mapOf("name" to it.name, "summary" to it.summary) },
            ),
        )

    @ExceptionHandler(
        PluginEmptyException::class,
        PluginTooLargeException::class,
        PluginNotJavaScriptException::class,
        PluginNotTextException::class,
        PluginContractException::class,
        PluginApiVersionUnsupportedException::class,
        
        PluginDeclarationInvalidException::class,
        
        PluginIdInvalidException::class,
        PluginFunctionInUseException::class,
        PluginPermissionUnknownException::class,
    )
    fun refused(failure: RuntimeException): ResponseEntity<Map<String, String>> =
        ResponseEntity.badRequest().body(mapOf("message" to (failure.message ?: "That file could not be loaded")))

    /**
     * The bytes as the text they are supposed to be.
     *
     * Strict decoding, so something that is not UTF-8 is refused here rather than
     * stored as replacement characters and puzzled over later.
     */
    private fun text(bytes: ByteArray): String = try {
        StandardCharsets.UTF_8.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT)
            .decode(java.nio.ByteBuffer.wrap(bytes))
            .toString()
    } catch (failure: CharacterCodingException) {
        throw PluginNotTextException()
    }

    private fun digest(source: String): String = MessageDigest.getInstance("SHA-256")
        .digest(source.toByteArray(StandardCharsets.UTF_8))
        .joinToString("") { "%02x".format(it) }

    private fun currentUser(): String =
        SecurityContextHolder.getContext().authentication?.name ?: "system"

    private companion object {
        /**
         * A plugin is a bundled script. Generous enough for one with its
         * dependencies compiled in, small enough that the row stays a row.
         */
        const val MAX_SIZE = 2L * 1024 * 1024

        const val MAX_NAME = 200

        /**
         * What a plugin may call itself: an identifier, and a short one.
         *
         * Short because it is the prefix on every function the plugin declares, and
         * a function name has 120 characters to fit in — 32 here leaves room for
         * the longest name a plugin could reasonably declare.
         */
        val KEY = Regex("[A-Za-z_$][A-Za-z0-9_$]{0,31}")

        /**
         * The starting point handed out by the button on the Plugins screen.
         *
         * Deliberately a plugin that already works: it answers the two questions
         * the server asks — which API it uses, and what it offers — so it can be
         * loaded unchanged and then edited into something useful.
         */
        val TEMPLATE = """
            /*
             * What the server provides. Declared, not imported: these exist before this
             * file is evaluated, and `declare` compiles to nothing — so an editor checks
             * your plugin against the real contract while the output stays what the
             * sandbox expects.
             */
            declare abstract class OrknuxPlugin {
              /** What this plugin calls itself, and the prefix on everything it declares. */
              abstract id(): string;
              /** Which plugin API this was written against. This server accepts @SUPPORTED@. */
              abstract apiVersion(): number;
              /** What this plugin offers. Defaults to none. */
              functions(): OrknuxFunction[];
              /** What this plugin has to be told before it can work. Defaults to none. */
              parameters(): OrknuxParameter[];
              /**
               * Which JavaScript this plugin needs. Defaults to none.
               *
               * A plugin embeds its libraries rather than importing them - that is
               * what makes it portable - and a bundle written for a browser or for
               * Node often expects language features this sandbox does not switch
               * on. Say which, and whoever loads the plugin is shown the list and
               * has to accept it. Nothing is relaxed that was not accepted, and
               * nothing is relaxed for any other plugin.
               *
               * This is the whole of what can be asked for:
               @PERMISSION_LIST@
               *
               * There is deliberately no name for reading a file, opening a socket
               * or reaching a Java class. Those are not permissions this list can
               * express, and asking for one is refused rather than half-granted.
               *
               * Loading is done with none of them granted, because that is the run
               * that finds out which you want - so the top level of your bundle has
               * to evaluate without them. Ask for what `run` needs, not for what
               * loading needs.
               */
              permissions(): OrknuxPermission[];
              /**
               * What a workspace set those parameters to, keyed by name.
               *
               * Frozen, and put there by the server for the length of one call. A
               * parameter nothing usable is set for is absent rather than null, so
               * `this.settings.token === undefined` is the question to ask.
               *
               * This is the whole of what a plugin knows about the workspace it is
               * running for. Nothing reaches a plugin that a workspace did not
               * point at, which is what makes the parameter list a readable answer
               * to "what can this thing get at?".
               */
              readonly settings: Readonly<Record<string, string | number | boolean>>;
            }

            /** The shape of a value crossing between a workflow and a plugin. */
            type OrknuxValueType = @VALUE_TYPE_UNION@;

            /** What a plugin may ask for. Exactly this list, and nothing else. */
            type OrknuxPermission = @PERMISSION_UNION@;

            declare class OrknuxFunction {
              constructor(declaration: {
                /** An identifier: letters, digits and underscores. */
                name: string;
                /** Optional; shown beside it in the interface. */
                description?: string;
                /** In the order `run` receives them. */
                params?: { name: string; type: OrknuxValueType }[];
                /** What it answers with. A function has to answer something. */
                returnType: OrknuxValueType;
                /** What it does. Stays here; the server calls back into it. */
                run: (...args: never[]) => unknown;
              });
            }

            /** What a parameter may be: exactly what a workspace variable can hold. */
            type OrknuxParameterType = @PARAMETER_TYPE_UNION@;

            declare class OrknuxParameter {
              constructor(declaration: {
                /** An identifier: letters, digits and underscores. */
                name: string;
                /** Optional; shown under it on the form somebody fills in. */
                description?: string;
                type: OrknuxParameterType;
                /**
                 * Whether the plugin can work without it. Defaults to true, because
                 * a parameter nobody needs is one nobody should be asked for.
                 *
                 * A workspace that has not answered a required one is marked as
                 * such in its plugin list and against the parameter itself.
                 */
                required?: boolean;
                /**
                 * Whether this is asking for something that should not be typed
                 * into a form. Defaults to false.
                 *
                 * Saying true refuses a typed-in value: the only way to answer it
                 * is to point at one of the workspace's variables, which is where
                 * this installation keeps things it encrypts.
                 */
                secret?: boolean;
              });
            }

            /**
             * An Orknux plugin: a class extending OrknuxPlugin, exported as the default.
             *
             * Nothing else is accepted — a plain object with the right keys is refused,
             * because the server checks the prototype rather than probing for methods it
             * hopes are there.
             */
            export default class Teammates extends OrknuxPlugin {

              /**
               * What this plugin calls itself. Its identity, not its filename: loading
               * this id again replaces whatever is loaded under it.
               *
               * Also the prefix on everything below, so `isTeammate` is offered to a
               * workflow as `teammates_isTeammate`. No default: leave it out and loading
               * fails saying so.
               */
              id(): string {
                return 'teammates';
              }

              /**
               * Which plugin API this was written against. This server accepts
               * @SUPPORTED@, and refuses anything else rather than guessing.
               */
              apiVersion(): number {
                return @API_VERSION@;
              }

              /**
               * What this plugin has to be told before it can work.
               *
               * Each workspace answers these once, either by typing a value or by
               * pointing at one of its own variables, and what they come to arrives as
               * `this.settings`. Declaring them is also how a workspace can see what
               * this plugin is able to reach: nothing gets in that is not on this list.
               *
               * Defaults to none, so a plugin that needs nothing says nothing.
               */
              parameters(): OrknuxParameter[] {
                return [
                  new OrknuxParameter({
                    name: 'teamDomain',
                    description: 'The mail domain this workspace treats as its own.',
                    type: 'string',
                  }),
                ];
              }

              /**
               * Which JavaScript this plugin needs beyond what every plugin gets.
               *
               * Whoever loads this is shown the list and has to accept it, and only
               * what was accepted is turned on - for this plugin, in the sandbox one
               * of its calls runs in, and nowhere else. Editing this to ask for more
               * means being asked again: the acceptance names the permissions it was
               * given for, so a new one is not covered by it.
               *
               * Leave it out if you need nothing, which is the common case.
               */
              permissions(): OrknuxPermission[] {
                return ['INTL'];
              }

              /**
               * What this plugin offers.
               *
               * Each one is checked as it is constructed — a missing name, return type
               * or `run` fails here, while you are looking at it, rather than on the way
               * into the database. Defaults to none: a plugin may exist for something
               * other than offering functions.
               */
              functions(): OrknuxFunction[] {
                return [
                  new OrknuxFunction({
                    name: 'isTeammate',
                    description: 'Whether an email address belongs to a member of this workspace.',
                    params: [{ name: 'email', type: 'string' }],
                    returnType: 'boolean',

                    /*
                     * `this.settings` is what the workspace answered, and it is all a
                     * function has beyond what it was passed. Reaching out — looking a
                     * user up in the directory, asking which workspace this is — is
                     * something the server has still to hand over.
                     *
                     * Written as an arrow function so `this` is the plugin. A method
                     * would work too; both are called with the plugin as `this`.
                     */
                    run: (email: string): boolean => {
                      if (typeof email !== 'string' || email.length === 0) {
                        return false;
                      }
                      const domain = this.settings.teamDomain;
                      if (typeof domain !== 'string') {
                        // Required, so a workspace that has not set it is already
                        // marked as needing to. Answering no is the safe reading.
                        return false;
                      }
                      return email.endsWith('@' + domain);
                    },
                  }),
                ];
              }
            }
        """
    }
}

/** Listing what is loaded, and taking one out. */
@Controller
class PluginAPI(
    private val plugins: PluginRepository,
    private val access: WorkspaceAccess,
    private val declarations: PluginDeclarations,
    private val registry: PluginFunctionRegistry,
    private val permissions: PluginPermissions,
) {

    /** Everything loaded into this installation, by name. */
    @QueryMapping
    fun plugins(): List<PluginView> {
        access.requireAdmin()
        return plugins.findAllByOrderByNameAsc().map {
            it.view(
                declarations.read(it.declaredFunctions),
                declarations.readParameters(it.declaredParameters),
                // What was accepted, shown to whoever is reading the list rather
                // than only to whoever accepted it. A decision about what code may
                // do that lives in a dialog is a decision nobody can audit.
                permissions.viewOf(permissions.grantedTo(it)),
            )
        }
    }

    /**
     * Takes a plugin out of the installation.
     *
     * Nothing refers to a plugin yet, so this is a delete. Once workflows can
     * point at what a plugin registers, this has to grow an in-use check and
     * leave something behind for a graph to render — removing a plugin out from
     * under a running workflow is not a thing to do quietly.
     */
    @MutationMapping
    @Transactional
    fun unloadPlugin(@Argument id: Long): Boolean {
        access.requireAdmin()
        val plugin = plugins.findByIdOrNull(id) ?: throw PluginNotFoundException(id)

        /*
         * Its functions go with it — the database cascades them — so anything still
         * calling one has to be dealt with first. Checked here rather than left to
         * the cascade, because a workflow pointing at a function that has stopped
         * existing fails at the moment it runs, which is the worst moment to learn.
         */
        val used = registry.inUse(plugin)
        if (used.isNotEmpty()) throw PluginInUseException(used)

        plugins.delete(plugin)
        return true
    }
}

/**
 * A workspace's side of a plugin: what it has been told, and what it has not.
 *
 * Separate from [PluginAPI] because the audience is: listing and unloading are an
 * administrator's, while answering what a plugin needs belongs to whoever runs the
 * workspace it will run for. The same plugin, two decisions, two sets of people.
 *
 * A plugin declaring no parameters still appears here. "This one needs nothing"
 * is an answer worth being able to read, and a plugin that grows a parameter
 * later should not appear out of nowhere.
 */
@Controller
class WorkspacePluginAPI(
    private val plugins: PluginRepository,
    private val parameters: PluginParameters,
    private val workspaces: WorkspaceRepository,
    private val access: WorkspaceAccess,
    private val auditRecorder: WorkspaceAuditRecorder,
) {

    /** Every loaded plugin, with what this workspace has set it to. */
    @QueryMapping
    fun workspacePlugins(@Argument workspaceId: Long): List<WorkspacePluginView> {
        requireWorkspaceAccess(workspaceId)
        return plugins.findAllByOrderByNameAsc().map { parameters.viewOf(it, workspaceId) }
    }

    /**
     * Answers one parameter, with a value or with one of the workspace's variables.
     *
     * Answers with the whole plugin rather than the one parameter, because setting
     * one changes whether the plugin is still marked as needing something - and a
     * screen that had to work that out for itself would eventually disagree with
     * the server about it.
     */
    @MutationMapping
    @Transactional
    fun setPluginParameter(
        @Argument workspaceId: Long,
        @Argument pluginId: Long,
        @Argument name: String,
        @Argument literal: String?,
        @Argument variableId: Long?,
    ): WorkspacePluginView {
        requireWorkspaceAccess(workspaceId)
        val plugin = plugins.findByIdOrNull(pluginId) ?: throw PluginNotFoundException(pluginId)

        parameters.set(plugin, workspaceId, name, literal?.trim()?.ifEmpty { null }, variableId, currentUser())

        /*
         * What it was set to is not recorded, only that it was. A literal is as
         * likely to be a hostname as the one piece of this that should never have
         * been typed in, and the audit log is read by more people than the
         * variables screen is.
         */
        auditRecorder.record(
            workspaceId,
            WorkspaceAuditCategory.INTEGRATION,
            "Plugin ${plugin.key}: parameter $name set",
        )
        return parameters.viewOf(plugin, workspaceId)
    }

    /** Unsets one parameter. A required one is marked as missing again. */
    @MutationMapping
    @Transactional
    fun clearPluginParameter(
        @Argument workspaceId: Long,
        @Argument pluginId: Long,
        @Argument name: String,
    ): WorkspacePluginView {
        requireWorkspaceAccess(workspaceId)
        val plugin = plugins.findByIdOrNull(pluginId) ?: throw PluginNotFoundException(pluginId)

        parameters.clear(plugin, workspaceId, name)
        auditRecorder.record(
            workspaceId,
            WorkspaceAuditCategory.INTEGRATION,
            "Plugin ${plugin.key}: parameter $name cleared",
        )
        return parameters.viewOf(plugin, workspaceId)
    }

    private fun requireWorkspaceAccess(workspaceId: Long) {
        access.requireVisible(workspaceId)
    }

    private fun currentUser(): String =
        SecurityContextHolder.getContext().authentication?.name ?: "system"
}

class PluginNotFoundException(id: Long) : RuntimeException("There is no plugin $id")

class PluginEmptyException : RuntimeException("That file is empty")

class PluginTooLargeException(maxKb: Long) : RuntimeException("A plugin may be at most $maxKb KB")

class PluginNotJavaScriptException(filename: String) :
    RuntimeException("$filename is not JavaScript; a plugin is a .js or .mjs file")

class PluginNotTextException : RuntimeException("That file is not UTF-8 text")

/**
 * The plugin never said which API it uses.
 *
 * The reason is passed on as the plugin gave it — no default export, no
 * `apiVersion` method, threw while loading — because that sentence is what tells
 * whoever wrote it what to change.
 */
class PluginApiVersionUnreadableException(reason: String) :
    RuntimeException("The plugin could not be asked which plugin API it uses: $reason")

/**
 * It is not a plugin, or it did not hold up the contract.
 *
 * The reason comes from the plugin's own sandbox — usually the base class saying
 * which method was not implemented — because that sentence is what tells whoever
 * wrote it what to change.
 */
class PluginContractException(reason: String) :
    RuntimeException("That file is not a usable plugin: $reason")

class PluginIdInvalidException(key: String) : RuntimeException(
    "\"$key\" cannot be a plugin id: it has to start with a letter and hold only " +
        "letters, digits or underscores, up to 32 of them — it becomes the prefix on " +
        "every function the plugin declares.",
)

class PluginApiVersionUnsupportedException(asked: Int, supported: Set<Int>) : RuntimeException(
    "The plugin uses plugin API version $asked, which this server does not know. " +
        "It supports ${supported.sorted().joinToString(", ")}.",
)

@Component
class PluginExceptionResolver : DataFetcherExceptionResolverAdapter() {

    override fun resolveToSingleError(exception: Throwable, environment: DataFetchingEnvironment): GraphQLError? {
        val errorType = when (exception) {
            is PluginEmptyException,
            is PluginTooLargeException,
            is PluginNotJavaScriptException,
            is PluginNotTextException,
            is PluginContractException,
            is PluginApiVersionUnsupportedException,
            
            is PluginDeclarationInvalidException,
            
            is PluginIdInvalidException,
            is PluginPermissionUnknownException,
            is PluginPermissionsNotAcceptedException,
            is PluginInUseException,
            is PluginFunctionInUseException,
            is PluginParameterUnknownException,
            is PluginParameterAmbiguousException,
            is PluginParameterEmptyException,
            is PluginParameterNotSecretException,
            is PluginParameterNotValueException,
            is PluginParameterVariableElsewhereException,
            -> ErrorType.BAD_REQUEST

            is PluginNotFoundException -> ErrorType.NOT_FOUND

            else -> return null
        }

        return GraphQLError.newError()
            .errorType(errorType)
            .message(exception.message)
            .path(environment.executionStepInfo.path)
            .location(environment.field.sourceLocation)
            .build()
    }
}
