package io.mszymanski.orknux.connector.model

import org.slf4j.LoggerFactory
import org.springframework.data.repository.findByIdOrNull
import org.springframework.stereotype.Service
import tools.jackson.databind.ObjectMapper
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.nio.charset.StandardCharsets
import java.time.Duration

/** What came back from a reading, or why nothing did. */
sealed interface Speech {

    /**
     * The audio itself, and what it is.
     *
     * The bytes are handed straight to whoever asked rather than stored: an
     * answer read aloud is listened to once, and keeping it would mean a second
     * copy of the conversation in a different medium.
     */
    data class Spoke(val audio: ByteArray, val contentType: String, val millis: Long) : Speech {

        /*
         * Generated by hand because the array makes the compiler's version wrong:
         * two readings of the same sentence are not the same object, and
         * `equals` comparing references would say they were different anyway.
         * Identity is what this has, so identity is what it declares.
         */
        override fun equals(other: Any?): Boolean = this === other

        override fun hashCode(): Int = System.identityHashCode(this)
    }

    data class Failed(val reason: String) : Speech
}

/**
 * Reads text aloud, using one of the workspace's models.
 *
 * The mirror of [ModelTranscriptionClient], and deliberately its twin: the same
 * providers, the same credential, the same failure vocabulary. OpenAI's
 * `/audio/speech` is the shape spoken by OpenAI itself, by Azure's OpenAI
 * deployments, and by the local servers that imitate them — a JSON body naming
 * the model, the text and a voice, answering with the audio as bytes.
 *
 * Unlike transcription this sends JSON rather than multipart, because what goes
 * up is a sentence; it is the answer that is binary.
 */
@Service
class ModelSpeechClient(
    private val providers: ModelProviderRepository,
    private val models: LlmModelRepository,
    private val probe: ModelProviderProbe,
    private val mapper: ObjectMapper,
) {

    private val http: HttpClient = HttpClient.newBuilder()
        .version(HttpClient.Version.HTTP_1_1)
        .connectTimeout(Duration.ofSeconds(CONNECT_SECONDS))
        .build()

    /**
     * @param modelId one of the workspace's models, which has to be a speech
     *   one: a chat model handed this would answer *about* the text instead of
     *   reading it.
     * @param voice which voice to use, or null for the model's own default —
     *   the providers disagree about what voices exist, so an installation that
     *   has not chosen one should not have a name invented for it.
     */
    fun speak(modelId: Long, text: String, voice: String?): Speech {
        val model = models.findByIdOrNull(modelId)
            ?: return Speech.Failed("That model no longer exists")
        if (model.kind != ModelKind.SPEECH) {
            return Speech.Failed("${model.name} is not a speech model")
        }
        if (!model.enabled) return Speech.Failed("${model.name} is turned off")

        val said = text.trim()
        if (said.isEmpty()) return Speech.Failed("There is nothing to read")

        val provider = providers.findByIdOrNull(model.providerId)
            ?: return Speech.Failed("The provider ${model.name} belongs to has been removed")

        val credential = when (val resolved = probe.credentials(provider)) {
            is ModelProviderProbe.Credential.Failed -> return Speech.Failed(resolved.reason)
            is ModelProviderProbe.Credential.Header -> resolved.header
        }

        val uri = try {
            URI("${provider.endpoint.trimEnd('/')}/audio/speech")
        } catch (_: Exception) {
            return Speech.Failed("The provider endpoint is not a usable URL")
        }

        val body = mapper.writeValueAsString(
            buildMap {
                put("model", model.modelId)
                put("input", said)
                put("response_format", FORMAT)
                voice?.takeIf { it.isNotBlank() }?.let { put("voice", it.trim()) }
            },
        )

        val request = HttpRequest.newBuilder(uri)
            // Generous for the same reason transcription is: a local model
            // synthesising a long answer is slow, and the alternative to waiting
            // is a button that fails on exactly the answers worth hearing.
            .timeout(Duration.ofSeconds(REQUEST_SECONDS))
            .header("Content-Type", "application/json")
            .header(credential.name, credential.value)
            .POST(HttpRequest.BodyPublishers.ofString(body, StandardCharsets.UTF_8))
            .build()

        val started = System.currentTimeMillis()
        return try {
            val answer = http.send(request, HttpResponse.BodyHandlers.ofByteArray())
            val millis = System.currentTimeMillis() - started
            if (answer.statusCode() !in 200..299) {
                log.warn("Speech by {} answered {}", model.name, answer.statusCode())
                return Speech.Failed("${model.name} answered ${answer.statusCode()}")
            }
            spoke(answer, millis, model.name)
        } catch (failure: Exception) {
            log.warn("Speech by {} could not be done", model.name, failure)
            Speech.Failed(failure.message ?: "The text could not be read")
        }
    }

    /**
     * The audio out of what the server answered.
     *
     * A provider that answered JSON answered a refusal rather than a recording,
     * whatever its status code said — some of them report a bad voice or an
     * unknown model with a 200 and an error object.
     */
    private fun spoke(answer: HttpResponse<ByteArray>, millis: Long, name: String): Speech {
        val audio = answer.body()
        if (audio.isEmpty()) return Speech.Failed("$name answered nothing")

        val contentType = answer.headers().firstValue("content-type").orElse("").lowercase()
        if (contentType.startsWith("application/json") || contentType.startsWith("text/")) {
            val said = runCatching {
                mapper.readTree(audio).path("error").path("message").stringValue()
            }.getOrNull()
            return Speech.Failed(said?.takeIf { it.isNotBlank() } ?: "$name answered something that was not audio")
        }

        return Speech.Spoke(
            audio = audio,
            contentType = contentType.ifEmpty { "audio/$FORMAT" },
            millis = millis,
        )
    }

    private companion object {
        val log = LoggerFactory.getLogger(ModelSpeechClient::class.java)

        /**
         * What to ask for.
         *
         * MP3 because every browser plays it, and because it is the one format
         * all of these providers offer — wav is smaller to decode but several
         * times the bytes over the wire for something that is only listened to.
         */
        const val FORMAT = "mp3"

        const val CONNECT_SECONDS = 10L
        const val REQUEST_SECONDS = 120L
    }
}
